// Hoja de estilos de la aplicación móvil (ticket ARC-001, paso 10).
//
// Compositor: fusiona módulos por dominio (`styles/merchant.ts`, `styles/customer.ts`, `styles/driver.ts`)
// antes de `StyleSheet.create`. Los imports existentes (`from "./styles"`) siguen igual.
//
// Se extrae primero por el mismo criterio que ordenó los pasos anteriores: el núcleo
// compartido sale antes que las superficies que lo consumen.
import { StyleSheet } from "react-native";

import { flashDesign } from "./design-system";

import { customerStyleDefs } from "./styles/customer";
import { driverStyleDefs } from "./styles/driver";
import { merchantStyleDefs } from "./styles/merchant";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f4f6f8",
  },
  appViewport: {
    flex: 1,
    width: "100%",
    alignSelf: "center",
    overflow: "hidden",
  },
  customerViewport: { maxWidth: 430, backgroundColor: "#fff" },
  operationsViewport: { maxWidth: 620, backgroundColor: "#f6f3f0" },
  loginSafeArea: { flex: 1, width: "100%", backgroundColor: "#f4f6f8" },
  networkStatusBanner: {
    position: "absolute",
    top: 8,
    left: 12,
    right: 12,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 10,
    borderRadius: 10,
    backgroundColor: "#7e2f24",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  networkStatusIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.16)",
  },
  networkStatusCopy: { flex: 1, minWidth: 0 },
  networkStatusTitle: { color: "#fff", fontSize: 12, fontWeight: "900" },
  networkStatusText: { color: "rgba(255,255,255,.82)", fontSize: 10, marginTop: 2 },
  customerRoot: { backgroundColor: "#eef0f3" },
  customerShell: {
    flex: 1,
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  customerScrollContent: {
    padding: flashDesign.space.md,
    paddingBottom: flashDesign.space.xl,
    backgroundColor: flashDesign.color.canvas,
  },
  header: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: "#161b22",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerCopy: { flex: 1, minWidth: 0 },
  eyebrow: {
    color: "#ffcc1c",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  title: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "900",
  },
  badge: {
    color: "#fff",
    backgroundColor: "#16a66a",
    borderRadius: 8,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "900",
  },
  tabs: {
    flexDirection: "row",
    gap: 8,
    padding: 12,
    backgroundColor: "#fff",
  },
  tab: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: "#f0f2f5",
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: {
    backgroundColor: "#f4511e",
  },
  tabText: {
    color: "#626a78",
    fontWeight: "900",
  },
  tabTextActive: {
    color: "#fff",
  },
  loader: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  muted: {
    color: "#626a78",
  },
  content: {
    padding: 14,
    paddingBottom: 40,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  customerContent: {
    maxWidth: 420,
    backgroundColor: "#fff",
    minHeight: "100%",
  },
  stack: {
    gap: 12,
  },
  logoutButton: {
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutText: { color: "#fff", fontWeight: "900" },
  sessionBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e8e5eb",
  },
  sessionRole: {
    color: "#f4511e",
    fontWeight: "900",
    textTransform: "uppercase",
    fontSize: 12,
  },
  sessionName: { color: "#17131c", fontWeight: "900" },
  loginRoot: {
    flex: 1,
    width: "100%",
    backgroundColor: flashDesign.color.ink,
    overflow: "hidden",
  },
  loginGlow: {
    position: "absolute",
    top: -116,
    right: -94,
    width: 290,
    height: 290,
    borderRadius: 145,
    backgroundColor: "rgba(163,112,255,.28)",
  },
  loginGlowSecondary: {
    position: "absolute",
    top: 210,
    left: -112,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "rgba(255,106,33,.16)",
  },
  loginScroll: { flex: 1, width: "100%" },
  loginContent: { flexGrow: 1, justifyContent: "flex-end", paddingTop: 12 },
  loginContentCompact: { paddingTop: 0 },
  loginHero: {
    minHeight: 292,
    paddingHorizontal: 24,
    paddingTop: 14,
    paddingBottom: 34,
    justifyContent: "space-between",
    gap: 24,
  },
  loginHeroCompact: {
    minHeight: 230,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 28,
    gap: 16,
  },
  loginBrandRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  loginMark: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
  },
  loginWordmark: { color: "#fff", fontSize: 22, fontWeight: "900", letterSpacing: -0.7 },
  loginSecurePill: {
    marginLeft: "auto",
    minHeight: 32,
    paddingHorizontal: 10,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,.1)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,.12)",
  },
  loginSecureText: { color: "#f5f1f8", fontSize: 11, fontWeight: "800" },
  loginHeroCopy: { gap: 8 },
  loginEyebrow: { color: "#d6ff72", fontSize: 11, fontWeight: "900", letterSpacing: 1.5 },
  loginTitle: {
    color: "#fff",
    fontSize: 40,
    lineHeight: 42,
    fontWeight: "900",
    letterSpacing: -1.8,
  },
  loginTitleCompact: { fontSize: 32, lineHeight: 34 },
  loginCopy: { maxWidth: 340, color: "rgba(255,255,255,.72)", fontSize: 14, lineHeight: 20 },
  loginServices: { flexDirection: "row", alignItems: "center", gap: 8 },
  loginService: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 34,
    paddingRight: 10,
    paddingLeft: 4,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,.09)",
  },
  loginServiceIcon: {
    width: 27,
    height: 27,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  loginServiceText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  loginCard: {
    width: "100%",
    minHeight: 420,
    paddingHorizontal: 24,
    paddingTop: 26,
    paddingBottom: 28,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#fff",
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
  },
  loginCardHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  loginBack: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f0f5",
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  loginCardHeading: { flex: 1, minWidth: 0, gap: 7 },
  loginCardTitle: {
    color: flashDesign.color.ink,
    fontSize: 27,
    lineHeight: 31,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  loginCardCopy: { color: "#716b75", fontSize: 13, lineHeight: 19 },
  loginIdentity: {
    minHeight: 54,
    borderRadius: 17,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#f6f3f8",
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  loginIdentityIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#efe8ff",
  },
  loginIdentityText: {
    flex: 1,
    minWidth: 0,
    color: flashDesign.color.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  loginIdentityAction: { color: flashDesign.color.brand, fontSize: 12, fontWeight: "900" },
  loginFieldGroup: { gap: 7 },
  loginLabelRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  loginFieldLabel: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  loginOptional: { color: "#8c8690", fontSize: 11, fontWeight: "700" },
  loginInlineAction: { color: flashDesign.color.brand, fontSize: 12, fontWeight: "900" },
  loginInputShell: {
    minHeight: 54,
    borderRadius: 17,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#faf9fb",
    borderWidth: 1.5,
    borderColor: "#dfdbe2",
  },
  loginInputShellError: { borderColor: flashDesign.color.danger, backgroundColor: "#fff8f7" },
  loginInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 13,
    color: flashDesign.color.ink,
    fontSize: 15,
    fontWeight: "600",
    outlineStyle: "none",
  } as never,
  loginCodeShell: {
    minHeight: 62,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#faf9fb",
    borderWidth: 1.5,
    borderColor: "#dfdbe2",
  },
  loginCodeInput: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    textAlign: "center",
    color: flashDesign.color.ink,
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 12,
    outlineStyle: "none",
  } as never,
  loginPasswordHint: { flexDirection: "row", alignItems: "center", gap: 5, paddingLeft: 2 },
  loginPasswordHintText: { color: "#7e7882", fontSize: 11, fontWeight: "700" },
  loginError: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 12,
    borderRadius: 14,
    backgroundColor: "#fff1ef",
    borderWidth: 1,
    borderColor: "#ffd1ca",
  },
  loginErrorText: {
    flex: 1,
    minWidth: 0,
    color: "#9b251b",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "800",
  },
  loginPrimary: {
    minHeight: 56,
    paddingHorizontal: 18,
    borderRadius: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: flashDesign.color.ink,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 3,
  },
  loginPrimaryDisabled: { backgroundColor: "#c9c4cd", shadowOpacity: 0, elevation: 0 },
  loginPrimaryPressed: { transform: [{ scale: 0.99 }], opacity: 0.94 },
  loginPrimaryText: { color: "#fff", fontSize: 15, fontWeight: "900" },
  loginSecondaryBlock: { gap: 13 },
  loginDivider: { flexDirection: "row", alignItems: "center", gap: 10 },
  loginDividerLine: { flex: 1, height: 1, backgroundColor: flashDesign.color.line },
  loginDividerText: { color: "#99939d", fontSize: 11, fontWeight: "800" },
  loginSecondary: {
    minHeight: 54,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: flashDesign.color.ink,
  },
  loginSecondaryPressed: { backgroundColor: "#f5f2f6" },
  loginSecondaryText: { color: flashDesign.color.ink, fontSize: 14, fontWeight: "900" },
  loginAudienceNote: {
    minHeight: 58,
    padding: 12,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#f6f3f8",
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  loginAudienceNoteIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ebe3ff",
  },
  loginAudienceNoteText: {
    flex: 1,
    minWidth: 0,
    color: "#665f69",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "700",
  },
  loginSwitch: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 38,
    paddingVertical: 5,
  },
  loginSwitchText: { color: "#706a74", fontSize: 13, fontWeight: "700" },
  loginSwitchStrong: { color: flashDesign.color.brand, fontWeight: "900" },
  loginVerificationActions: { flexDirection: "row", justifyContent: "center", gap: 12 },
  loginLegal: {
    color: "#9a949e",
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
    paddingHorizontal: 8,
  },
  serviceNav: {
    flexDirection: "row",
    gap: flashDesign.space.xs,
    padding: 5,
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 2,
  },
  serviceNavItem: {
    flex: 1,
    minHeight: 62,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  serviceNavItemActive: { backgroundColor: flashDesign.color.ink },
  serviceIconBubble: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: flashDesign.color.warningSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  serviceIconBubbleActive: { backgroundColor: flashDesign.color.food },
  serviceNavText: { color: "#625b69", fontSize: 12, fontWeight: "900" },
  serviceNavTextActive: { color: "#fff" },
  foodHero: {
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#ff6a21",
    gap: 10,
  },
  foodHeroTitle: { color: "#fff", fontSize: 28, fontWeight: "900" },
  foodTopbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: flashDesign.space.sm,
    paddingTop: 2,
  },
  foodLocationBlock: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 10 },
  foodLocationIcon: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodLocationCopy: { flex: 1, minWidth: 0, gap: 2 },
  foodTopActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  foodAvatar: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEE7FF",
    borderWidth: 1,
    borderColor: "#DED0FF",
  },
  foodAvatarText: { color: flashDesign.color.brandDeep, fontSize: 16, fontWeight: "900" },
  foodDeliverLabel: {
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  foodAddress: {
    color: flashDesign.color.ink,
    fontSize: 13,
    fontWeight: "900",
  },
  foodCartIcon: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 17,
    backgroundColor: flashDesign.color.ink,
    alignItems: "center",
    justifyContent: "center",
  },
  foodCartCount: {
    position: "absolute",
    right: -4,
    top: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: flashDesign.color.food,
    color: "#fff",
    fontSize: 10,
    textAlign: "center",
    paddingTop: 2,
    overflow: "hidden",
  },
  ...customerStyleDefs,
  ...merchantStyleDefs,
  ...driverStyleDefs,
  // Cast: los módulos por dominio exportan literales string que TS ensancha y
  // StyleSheet.create rechaza (flexDirection/overflow Image vs View).
} as any);
