// Cuenta: actividad, pagos, soporte, direcciones, dieta y pedidos activos.
// Estilos del cliente móvil — módulo ARC-001 (paso 10d).
import { flashDesign } from "../design-system";

export const customerAccountStyleDefs = {
  activityHeading: { paddingVertical: 10, gap: 4 },
  customerAccountHeading: {
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  customerLogoutButton: {
    minHeight: 44,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#dedbe1",
    backgroundColor: "#fff",
  },
  customerLogoutText: { color: "#27242a", fontSize: 13, fontWeight: "900" },
  activityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  activityIconFood: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#ff6a21",
    alignItems: "center",
    justifyContent: "center",
  },
  activityIconRide: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionSectionTitle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 8,
  },
  substitutionCount: {
    minWidth: 30,
    height: 30,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: "#ff6a21",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionCountText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  substitutionCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 15,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ffd8c4",
    shadowColor: "#7c3cff",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  substitutionAlert: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionContent: { flex: 1, gap: 10 },
  substitutionEyebrow: {
    color: "#ff6a21",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  substitutionTitle: { color: "#211d24", fontSize: 18, fontWeight: "900" },
  substitutionArrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 11,
    borderRadius: 16,
    backgroundColor: "#f8f5fb",
  },
  substitutionProduct: { flex: 1, gap: 2 },
  substitutionPrice: { color: "#211d24", fontSize: 13, fontWeight: "900" },
  substitutionReason: { color: "#736d77", fontSize: 12, lineHeight: 17 },
  substitutionRefund: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    padding: 10,
    borderRadius: 13,
    backgroundColor: "#e6f8ef",
  },
  substitutionRefundText: { flex: 1, color: "#087a50", fontSize: 12, fontWeight: "800" },
  substitutionActions: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  substitutionReject: {
    flex: 1,
    minHeight: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ddd6e2",
    backgroundColor: "#fff",
  },
  substitutionRejectText: { color: "#554f59", fontSize: 12, fontWeight: "900" },
  substitutionAccept: {
    flex: 1.35,
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    backgroundColor: "#ff6a21",
  },
  substitutionAcceptText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  reportIssueButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "#fff4f1",
    borderWidth: 1,
    borderColor: "#ffd9d1",
  },
  reportIssueText: { flex: 1, color: "#a63e2c", fontSize: 12, fontWeight: "900" },
  issueModalBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(24,18,27,.52)",
  },
  issueModalSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "90%",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 28,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  issueModalHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 4,
    backgroundColor: "#ddd6e0",
  },
  issueModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  issueModalClose: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#f5f1f6",
  },
  issueCategoryRail: { gap: 8, paddingVertical: 2 },
  issueCategoryPill: {
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#e4dde7",
    backgroundColor: "#fff",
  },
  issueCategoryPillActive: { borderColor: "#ff6a21", backgroundColor: "#fff3ec" },
  issueCategoryText: { color: "#706872", fontSize: 11, fontWeight: "800" },
  issueCategoryTextActive: { color: "#d84d11" },
  issueFieldLabel: { color: "#302a32", fontSize: 12, fontWeight: "900" },
  issueDescriptionInput: { minHeight: 96, textAlignVertical: "top", paddingTop: 12 },
  issueMoneyInput: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e4dde7",
    borderRadius: 15,
    backgroundColor: "#faf8fb",
  },
  issueMoneyPrefix: { color: "#211d24", fontSize: 20, fontWeight: "900" },
  issueMoneyTextInput: {
    flex: 1,
    paddingHorizontal: 8,
    color: "#211d24",
    fontSize: 20,
    fontWeight: "900",
  },
  issueSecurityNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 11,
    borderRadius: 14,
    backgroundColor: "#eaf8f1",
  },
  issueSecurityText: { flex: 1, color: "#087a50", fontSize: 11, lineHeight: 16, fontWeight: "700" },
  issueSubmitButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 16,
    backgroundColor: "#ff6a21",
  },
  issueSubmitText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  accountCard: {
    alignItems: "center",
    gap: 8,
    padding: 22,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  accountAvatar: {
    width: 74,
    height: 74,
    borderRadius: 28,
    backgroundColor: "#efe7ff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
  },
  accountInitial: { color: "#7c3cff", fontSize: 30, fontWeight: "900" },
  accountDetail: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    borderRadius: 15,
    backgroundColor: "#f7f5f8",
    marginTop: 5,
  },
  addressBookCard: {
    gap: 14,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  addressBookHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  savedAddressRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 11,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0edf2",
  },
  savedAddressIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0eaff",
  },
  savedAddressIconDefault: { backgroundColor: "#7c3cff" },
  savedAddressCopy: { flex: 1, minWidth: 180, gap: 3 },
  savedAddressTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  addressValidationStatus: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 3 },
  addressValidationText: { color: "#087a50", fontSize: 11, fontWeight: "800" },
  addressValidationTextWarning: { color: "#a15c00" },
  defaultAddressBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    color: "#6d35dc",
    backgroundColor: "#efe7ff",
    borderRadius: 999,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  savedAddressActions: { flexDirection: "row", alignItems: "center", gap: 13 },
  newAddressForm: { gap: 11, paddingTop: 5 },
  addressMatchList: {
    gap: 7,
    padding: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e8e0f4",
    backgroundColor: "#faf8fc",
  },
  addressMatchHint: { color: "#6f6872", fontSize: 11, fontWeight: "700" },
  addressMatchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#fff",
  },
  addressMatchIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0eaff",
  },
  addressMatchCopy: { flex: 1, gap: 2 },
  addressMatchLabel: { color: "#2f2a32", fontSize: 13, fontWeight: "800" },
  addressMatchMeta: { color: "#8a838d", fontSize: 10, fontWeight: "600" },
  addressSelectedNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#eaf8f1",
  },
  addressSelectedText: { flex: 1, color: "#087a50", fontSize: 11, fontWeight: "700" },
  paymentMethodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0edf2",
  },
  paymentBrandRail: { gap: 8, paddingVertical: 2 },
  paymentCompactFields: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  paymentCompactInput: { flex: 1, minWidth: 140 },
  notificationBell: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 13,
    borderRadius: 17,
    backgroundColor: "#faf8fb",
  },
  notificationUnread: { backgroundColor: "#f3edff", borderWidth: 1, borderColor: "#dfd0ff" },
  notificationStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#7c3cff",
    marginTop: 6,
  },
  notificationTime: { fontSize: 11, color: "#9c989f", marginTop: 3 },
  notificationNew: { fontSize: 9, fontWeight: "900", color: "#7c3cff", letterSpacing: 0.8 },
  notificationEmpty: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#eefaf5",
  },
  preferenceGroup: { gap: 9, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#f0edf2" },
  preferenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  preferenceSwitch: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ded9e1",
    padding: 3,
  },
  preferenceSwitchActive: { backgroundColor: "#7c3cff" },
  preferenceKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: "#fff" },
  preferenceKnobActive: { alignSelf: "flex-end" },
  supportTicketCard: {
    gap: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#faf8fb",
    borderWidth: 1,
    borderColor: "#ece7ef",
  },
  supportTicketHeader: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  supportSla: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    color: "#087a50",
    backgroundColor: "#e5f8f0",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 9,
  },
  supportSlaLate: { color: "#b3302c", backgroundColor: "#ffe9e7" },
  supportMessages: { gap: 7 },
  supportMessage: { maxWidth: "88%", paddingHorizontal: 11, paddingVertical: 8, borderRadius: 14 },
  supportMessageOwn: { alignSelf: "flex-end", backgroundColor: "#7c3cff" },
  supportMessageStaff: { alignSelf: "flex-start", backgroundColor: "#ece8ef" },
  supportMessageText: { fontSize: 13, color: "#262128" },
  supportMessageTextOwn: { color: "#fff" },
  supportMessageTime: { fontSize: 9, color: "#9c989f", marginTop: 3 },
  supportReplyRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  supportReplyInput: { flex: 1 },
  supportSendButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  complianceCard: {
    gap: 13,
    padding: 17,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e4ec",
  },
  deliveryProofCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#f7f1ff",
    borderWidth: 1,
    borderColor: "#e3d3ff",
  },
  deliveryProofIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7c3cff",
  },
  deliveryEvidenceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#e8f7f0",
  },
  deliveryEvidenceBadgeText: { fontSize: 12, fontWeight: "800", color: "#087a50" },
  productCustomizerBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(20,16,24,.56)",
  },
  productCustomizerSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "92%",
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 28,
    gap: 14,
    borderTopLeftRadius: flashDesign.radius.sheet,
    borderTopRightRadius: flashDesign.radius.sheet,
    backgroundColor: flashDesign.color.canvas,
  },
  productCustomizerHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#D5CFD8",
  },
  productCustomizerHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  productCustomizerEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  productCustomizerTitle: {
    color: flashDesign.color.ink,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: "900",
    letterSpacing: -0.4,
    marginTop: 2,
  },
  productCustomizerRestaurant: { color: flashDesign.color.inkSoft, fontSize: 10, marginTop: 3 },
  productCustomizerContent: { gap: 13, paddingBottom: 6 },
  productCustomizerSummary: {
    minHeight: 100,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 10,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  productCustomizerImage: { width: 82, height: 82, borderRadius: 16 },
  productCustomizerSummaryPrice: {
    color: flashDesign.color.foodDeep,
    fontSize: 17,
    fontWeight: "900",
  },
  productCustomizerSummaryDescription: {
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 4,
  },
  productCustomizerWarningIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.7)",
  },
  foodCustomizerGroup: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCustomizerGroupHeader: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    backgroundColor: "#FBF9FC",
  },
  foodCustomizerGroupTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  foodCustomizerGroupTitle: { color: flashDesign.color.ink, fontSize: 14, fontWeight: "900" },
  foodCustomizerGroupMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCustomizerRequirement: {
    color: flashDesign.color.inkSoft,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.surfaceMuted,
  },
  foodCustomizerRequirementRequired: {
    color: flashDesign.color.foodDeep,
    backgroundColor: flashDesign.color.warningSoft,
  },
  dietaryBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  dietaryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#e9f8ef",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  dietaryBadgeText: { color: "#087a50", fontSize: 12, fontWeight: "800" },
  dietaryPreferenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 8,
    marginBottom: 14,
  },
  dietaryPreferenceChip: {
    borderWidth: 1,
    borderColor: "#ddd9e1",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  dietaryPreferenceChipActive: { backgroundColor: "#e9f8ef", borderColor: "#8ed5aa" },
  dietaryAllergenChipActive: { backgroundColor: "#fff0e6", borderColor: "#ffb47b" },
  dietaryPreferenceText: { fontSize: 12, fontWeight: "800", color: "#6a6570" },
  dietaryPreferenceTextActive: { color: "#087a50" },
  dietaryAllergenTextActive: { color: "#a3480a" },
  dietarySafetyNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#fff8eb",
    borderRadius: 12,
    padding: 10,
    marginTop: 10,
  },
  dietaryFilterBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#e9f8ef",
    borderRadius: 12,
    padding: 10,
  },
  searchStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    padding: 22,
    backgroundColor: "#f8f7f9",
    borderRadius: 16,
  },
  searchMatchText: { fontSize: 11, color: "#8a6578", marginTop: 3 },
  searchMoreButton: {
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffb992",
    borderRadius: 14,
    padding: 13,
  },
  searchMoreText: { color: "#d64c0b", fontWeight: "900" },
  orderConfirmationCard: {
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#FFD0AF",
    borderRadius: flashDesign.radius.surface,
    padding: 22,
    marginBottom: 4,
  },
  orderConfirmationIcon: {
    width: 58,
    height: 58,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 3,
  },
  orderConfirmationEyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.4,
    color: flashDesign.color.foodDeep,
    marginTop: 3,
  },
  orderConfirmationTitle: {
    color: flashDesign.color.ink,
    fontSize: 21,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: -0.4,
  },
  orderConfirmationCopy: {
    maxWidth: 290,
    color: flashDesign.color.inkSoft,
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  orderConfirmationTotal: {
    color: flashDesign.color.ink,
    fontSize: 25,
    fontWeight: "900",
    marginVertical: 3,
  },
  orderConfirmationAction: {
    width: "100%",
    minHeight: 50,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: flashDesign.color.ink,
    borderRadius: 16,
    padding: 13,
    marginTop: 6,
  },
  orderConfirmationActionText: { color: "#fff", fontWeight: "900" },
  foodActiveOrderCard: {
    gap: 12,
    padding: 14,
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  foodActiveOrderHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  foodActiveOrderIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.food,
  },
  foodActiveOrderEyebrow: {
    color: flashDesign.color.muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  foodActiveOrderStatus: {
    color: flashDesign.color.ink,
    fontSize: 15,
    fontWeight: "900",
    marginTop: 2,
  },
  foodActiveOrderEta: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodActiveOrderDestination: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 15,
    backgroundColor: flashDesign.color.canvas,
  },
  foodActiveOrderDestinationText: {
    flex: 1,
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 14,
  },
  foodActiveOrderTotal: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodActiveOrderActions: { flexDirection: "row", gap: 8 },
  foodActiveOrderSecondary: {
    flex: 1,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FFD7C2",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodActiveOrderSecondaryText: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  foodActiveOrderPrimary: {
    flex: 1.3,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    backgroundColor: flashDesign.color.ink,
  },
  foodActiveOrderPrimaryText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  foodActiveOrderCancel: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 11,
    borderTopWidth: 1,
    borderTopColor: flashDesign.color.line,
  },
  foodActiveOrderCancelText: { color: flashDesign.color.danger, fontSize: 10, fontWeight: "800" },
  reorderButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: "#ff6a21",
    borderRadius: 13,
    padding: 12,
    marginTop: 12,
  },
  reorderButtonText: { color: "#fff", fontWeight: "900" },
};
