// Comidas: home, búsqueda, restaurante, carrito y navegación inferior.
// Estilos del cliente móvil — módulo ARC-001 (paso 10d).
import { flashDesign } from "../design-system";

export const customerFoodStyleDefs = {
  foodHomeHeading: { gap: 3, paddingTop: 6, paddingBottom: 2 },
  foodHomeEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  foodHomeTitle: {
    color: flashDesign.color.ink,
    fontSize: flashDesign.type.display,
    lineHeight: 35,
    fontWeight: "900",
    letterSpacing: -1,
  },
  foodPromoBanner: {
    minHeight: 186,
    borderRadius: flashDesign.radius.surface,
    padding: 18,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "stretch",
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 22,
    elevation: 4,
  },
  foodPromoCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 7,
    zIndex: 2,
  },
  foodPromoBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.12)",
  },
  foodPromoBadgeText: {
    color: "#FFD6C2",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  foodPromoTitle: {
    color: "#fff",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  foodPromoDescription: { color: "rgba(255,255,255,.72)", fontSize: 12, lineHeight: 17 },
  foodPromoAction: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 13,
    borderRadius: 12,
    backgroundColor: "#fff",
    marginTop: 2,
  },
  foodPromoActionText: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodPromoArt: {
    width: 90,
    alignItems: "center",
    justifyContent: "center",
    marginRight: -4,
    transform: [{ rotate: "-7deg" }],
    borderRadius: 32,
    backgroundColor: flashDesign.color.food,
  },
  foodPromoArtDot: {
    position: "absolute",
    right: -18,
    bottom: -20,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(255,255,255,.18)",
  },
  foodSearchButton: {
    minHeight: 54,
    borderRadius: 18,
    paddingLeft: 15,
    paddingRight: 7,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  foodSearchPlaceholder: { color: flashDesign.color.muted, flex: 1, fontSize: 13 },
  foodSearchFilter: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.ink,
  },
  foodSearchInput: { color: "#252128", flex: 1, minHeight: 46 },
  foodSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  foodSectionTitle: {
    color: flashDesign.color.ink,
    fontSize: flashDesign.type.section,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  foodSeeAll: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "800" },
  foodCategoryRail: { gap: 10, paddingVertical: 4, paddingRight: 4 },
  foodCategoryItem: { width: 76, alignItems: "center", gap: 7 },
  foodCategoryArt: {
    width: 68,
    height: 68,
    borderRadius: 23,
    backgroundColor: flashDesign.color.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCategoryArtActive: {
    borderColor: flashDesign.color.food,
    borderWidth: 2,
    shadowColor: flashDesign.color.food,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 2,
  },
  foodCategoryImage: { width: 60, height: 60, borderRadius: 19 },
  foodCategoryName: {
    minHeight: 28,
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  foodCategoryNameActive: { color: flashDesign.color.foodDeep, fontWeight: "900" },
  foodFavoriteRail: { gap: 12, paddingRight: 4, paddingBottom: 2 },
  foodFavoriteCard: {
    width: 166,
    padding: 7,
    borderRadius: 19,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodFavoriteImage: { height: 94, padding: 7, alignItems: "flex-end" },
  foodFavoriteImageStyle: { borderRadius: 14 },
  foodFavoriteEta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.94)",
  },
  foodFavoriteEtaText: { color: flashDesign.color.ink, fontSize: 9, fontWeight: "900" },
  foodFavoriteName: {
    color: flashDesign.color.ink,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 7,
    paddingHorizontal: 2,
  },
  foodFavoriteMeta: {
    color: flashDesign.color.muted,
    fontSize: 10,
    marginTop: 2,
    paddingHorizontal: 2,
    paddingBottom: 2,
  },
  foodOffer: {
    minHeight: 112,
    borderRadius: 22,
    padding: 17,
    backgroundColor: "#ffad25",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  foodOfferKicker: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  foodOfferTitle: {
    color: "#fff",
    fontSize: 23,
    fontWeight: "900",
    marginTop: 3,
  },
  foodOfferCopy: { color: "rgba(255,255,255,.85)", marginTop: 4 },
  foodPopularRail: { gap: 12, paddingBottom: 3 },
  foodPopularCard: {
    width: 150,
    padding: 8,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eee9ec",
  },
  foodPopularImage: {
    height: 104,
    borderRadius: 14,
    padding: 8,
    alignItems: "flex-end",
  },
  foodPopularImageStyle: { borderRadius: 14 },
  foodPopularEta: {
    color: "#252128",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
  },
  foodPopularName: { color: "#252128", fontWeight: "900", marginTop: 8 },
  foodPopularRestaurant: { color: "#88838a", fontSize: 11, marginTop: 2 },
  foodMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
  },
  foodRating: { color: "#ff6a21", fontWeight: "900" },
  foodMetaItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  foodMetaText: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "700" },
  foodMetaDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: "#C3BDC7" },
  foodHeart: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: flashDesign.color.ink,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  foodPageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 50,
  },
  foodPageHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  foodBack: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 16,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    alignItems: "center",
    justifyContent: "center",
  },
  foodPageTitle: {
    color: flashDesign.color.ink,
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  foodPageSubtitle: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "700" },
  foodSearchClear: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surfaceMuted,
  },
  foodSearchCategoryRail: { gap: 10, paddingRight: 4, paddingBottom: 2 },
  foodSearchCategoryCard: {
    width: 126,
    padding: 8,
    borderRadius: 18,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchCategoryImage: { width: "100%", height: 74, borderRadius: 13 },
  foodSearchCategoryImageFallback: {
    width: "100%",
    height: 74,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodSearchCategoryName: {
    minHeight: 30,
    color: flashDesign.color.ink,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
    marginTop: 7,
  },
  foodSearchCategoryCount: {
    color: flashDesign.color.muted,
    fontSize: 9,
    fontWeight: "700",
    marginTop: 2,
  },
  foodSearchSkeletonList: { gap: 10 },
  foodSearchSkeletonCard: {
    minHeight: 110,
    flexDirection: "row",
    gap: 12,
    padding: 9,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchSkeletonImage: { width: 98, borderRadius: 14, backgroundColor: "#E9E5EC" },
  foodSearchSkeletonCopy: { flex: 1, justifyContent: "center", gap: 9 },
  foodSearchSkeletonTitle: {
    width: "72%",
    height: 14,
    borderRadius: 7,
    backgroundColor: "#E6E1E9",
  },
  foodSearchSkeletonLine: { width: "92%", height: 10, borderRadius: 5, backgroundColor: "#EEEAF0" },
  foodSearchSkeletonShort: {
    width: "52%",
    height: 10,
    borderRadius: 5,
    backgroundColor: "#EEEAF0",
  },
  foodSearchState: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    padding: 22,
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchStateIcon: {
    width: 54,
    height: 54,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodSearchStateTitle: { color: flashDesign.color.ink, fontSize: 17, fontWeight: "900" },
  foodSearchStateCopy: {
    maxWidth: 270,
    color: flashDesign.color.inkSoft,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  foodSearchRetry: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    borderRadius: 13,
    backgroundColor: flashDesign.color.ink,
    marginTop: 2,
  },
  foodSearchRetryText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  foodSearchResultCard: {
    overflow: "hidden",
    borderRadius: 21,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 15,
    elevation: 2,
  },
  foodSearchResultImage: { height: 148, padding: 10, alignItems: "flex-end" },
  foodSearchResultEta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.95)",
  },
  foodSearchResultEtaText: { color: flashDesign.color.ink, fontSize: 10, fontWeight: "900" },
  foodSearchResultBody: { gap: 6, padding: 13 },
  foodSearchResultHeading: { flexDirection: "row", alignItems: "center", gap: 8 },
  foodSearchResultName: { flex: 1, color: flashDesign.color.ink, fontSize: 16, fontWeight: "900" },
  foodSearchResultCuisine: { color: flashDesign.color.inkSoft, fontSize: 11 },
  foodSearchResultMeta: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  foodSearchResultMetaText: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "700" },
  foodSearchResult: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 10,
  },
  foodResultImage: { width: 70, height: 62, borderRadius: 13 },
  foodRestaurantHero: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: flashDesign.radius.surface,
    overflow: "hidden",
    padding: 13,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  foodRestaurantHeroImage: { borderRadius: flashDesign.radius.surface },
  foodFloatingButton: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: flashDesign.color.ink,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 2,
  },
  foodRestaurantInfo: {
    backgroundColor: flashDesign.color.surface,
    borderRadius: flashDesign.radius.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 17,
    marginTop: -26,
    marginHorizontal: 10,
    gap: 9,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 4,
  },
  foodRestaurantStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  foodRestaurantOpenBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: flashDesign.color.successSoft,
  },
  foodRestaurantOpenDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: flashDesign.color.shipment,
  },
  foodRestaurantOpenText: {
    color: flashDesign.color.shipment,
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  foodRestaurantOfferBadge: {
    maxWidth: "58%",
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodRestaurantTitle: {
    color: flashDesign.color.ink,
    fontSize: 23,
    lineHeight: 28,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  foodRestaurantCuisine: { color: flashDesign.color.inkSoft, fontSize: 11, lineHeight: 16 },
  foodRestaurantFacts: { flexDirection: "row", gap: 8, paddingTop: 3 },
  foodRestaurantFact: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    padding: 8,
    borderRadius: 14,
    backgroundColor: flashDesign.color.canvas,
  },
  foodRestaurantFactIcon: {
    width: 30,
    height: 30,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
  },
  foodRestaurantFactValue: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodRestaurantFactLabel: { color: flashDesign.color.muted, fontSize: 8, marginTop: 1 },
  foodMenuTabs: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 2,
    paddingRight: 4,
  },
  foodMenuTabButton: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodMenuTabButtonActive: {
    backgroundColor: flashDesign.color.ink,
    borderColor: flashDesign.color.ink,
  },
  foodMenuTab: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "800" },
  foodMenuTabActive: {
    color: "#fff",
    fontWeight: "900",
  },
  foodProductCard: {
    minHeight: 122,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: flashDesign.color.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 9,
  },
  foodProductImage: {
    width: 104,
    height: 104,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  foodProductImageStyle: { borderRadius: 16 },
  foodProductUnavailable: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(23,19,28,.78)",
  },
  foodProductUnavailableText: { color: "#fff", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  foodProductHeading: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  foodProductName: {
    flex: 1,
    color: flashDesign.color.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  foodProductDescription: { color: flashDesign.color.inkSoft, fontSize: 10, lineHeight: 14 },
  foodProductPrice: { color: flashDesign.color.foodDeep, fontWeight: "900", marginTop: 3 },
  foodAddButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: flashDesign.color.food,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
  },
  foodAddButtonDisabled: { backgroundColor: "#C8C2CB" },
  foodStickyCart: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: "#ff6a21",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 12,
  },
  foodStickyCount: {
    width: 30,
    height: 30,
    borderRadius: 10,
    paddingTop: 5,
    textAlign: "center",
    color: "#ff6a21",
    backgroundColor: "#fff",
    fontWeight: "900",
    overflow: "hidden",
  },
  foodStickyLabel: { color: "#fff", fontWeight: "900", flex: 1 },
  foodStickyPrice: { color: "#fff", fontWeight: "900" },
  foodCartMerchant: {
    minHeight: 86,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 10,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCartMerchantImage: { width: 66, height: 66, borderRadius: 16 },
  foodCartMerchantEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
  },
  foodCartMerchantName: {
    color: flashDesign.color.ink,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 2,
  },
  foodCartMerchantMeta: { color: flashDesign.color.inkSoft, fontSize: 10, marginTop: 3 },
  foodCartLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: flashDesign.color.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 11,
  },
  foodCartLineIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartLineName: { color: flashDesign.color.ink, fontSize: 13, fontWeight: "900" },
  foodCartLineMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 2 },
  foodCartLineNote: {
    color: flashDesign.color.inkSoft,
    fontSize: 9,
    lineHeight: 13,
    fontStyle: "italic",
    marginTop: 2,
  },
  foodQuantity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 15,
    backgroundColor: flashDesign.color.canvas,
    padding: 4,
  },
  foodQuantityButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodQuantityButtonAdd: {
    backgroundColor: flashDesign.color.food,
    borderColor: flashDesign.color.food,
  },
  foodQuantityValue: {
    minWidth: 18,
    color: flashDesign.color.ink,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  foodTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  foodCartOptionList: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCartOption: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 11,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
    backgroundColor: flashDesign.color.surface,
  },
  foodCartOptionSelected: { backgroundColor: "#FFF9F5" },
  foodCartOptionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartOptionIconSelected: { backgroundColor: flashDesign.color.food },
  foodCartPaymentIcon: { backgroundColor: "#EEE7FF" },
  foodCartPaymentIconSelected: { backgroundColor: flashDesign.color.brand },
  foodCartOptionTitleRow: { flexDirection: "row", alignItems: "center", gap: 7, flexWrap: "wrap" },
  foodCartOptionTitle: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodCartOptionMeta: {
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
  foodCartDefaultBadge: {
    color: flashDesign.color.foodDeep,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.5,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartMissingOption: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    backgroundColor: "#FFF4F2",
  },
  foodCouponField: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingLeft: 8,
    paddingRight: 7,
    borderRadius: 18,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCouponIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCouponInput: {
    flex: 1,
    minHeight: 50,
    color: flashDesign.color.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  foodCartTotalCard: {
    minHeight: 92,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    padding: 15,
    borderRadius: 20,
    backgroundColor: flashDesign.color.ink,
  },
  foodCartTotalLabel: { color: "#FFD4BF", fontSize: 9, fontWeight: "900", letterSpacing: 1 },
  foodCartTotalHelp: {
    maxWidth: 210,
    color: "rgba(255,255,255,.62)",
    fontSize: 9,
    lineHeight: 13,
    marginTop: 5,
  },
  foodCartTotalValue: { color: "#fff", fontSize: 22, fontWeight: "900" },
  foodCheckoutPrimary: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 15,
    borderRadius: 17,
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 3,
  },
  foodCheckoutPrimaryText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  foodEmpty: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    backgroundColor: flashDesign.color.surface,
    borderRadius: flashDesign.radius.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 24,
  },
  foodEmptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodEmptyTitle: {
    color: flashDesign.color.ink,
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  foodEmptyCopy: {
    maxWidth: 280,
    color: flashDesign.color.inkSoft,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  foodEmptyAction: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: flashDesign.color.ink,
  },
  foodEmptyActionText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  foodBottomNav: {
    flexDirection: "row",
    minHeight: 68,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#eee9ec",
    marginHorizontal: 14,
    marginBottom: 8,
    paddingHorizontal: 6,
    shadowColor: "#241a28",
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  foodBottomItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  foodBottomLabel: { color: "#9c989f", fontSize: 10, fontWeight: "700" },
  foodBottomLabelActive: { color: "#ff6a21" },
  shareAction: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 13,
    backgroundColor: "#fff7f2",
    borderWidth: 1,
    borderColor: "#ffe0cf",
  },
  shareActionText: { color: "#ff6a21", fontSize: 12, fontWeight: "900" },
};
