// Estilos del cliente móvil — Comidas, cuenta, checkout (ARC-001, paso 10c).
// Extraídos de `styles.ts`; se fusionan en el compositor vía spread.
import { flashDesign } from "../design-system";

export const customerStyleDefs = {
  foodHomeHeading: { gap: 3, paddingTop: 6, paddingBottom: 2 },
  foodHomeEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  foodHomeTitle: {
    color: flashDesign.color.ink,
    fontSize: flashDesign.type.display,
    lineHeight: 35,
    fontWeight: "900",
    letterSpacing: -1,
  },
  foodPromoBanner: {
    minHeight: 186,
    borderRadius: flashDesign.radius.surface,
    padding: 18,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "stretch",
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 22,
    elevation: 4,
  },
  foodPromoCopy: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 7,
    zIndex: 2,
  },
  foodPromoBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.12)",
  },
  foodPromoBadgeText: {
    color: "#FFD6C2",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  foodPromoTitle: {
    color: "#fff",
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  foodPromoDescription: { color: "rgba(255,255,255,.72)", fontSize: 12, lineHeight: 17 },
  foodPromoAction: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 13,
    borderRadius: 12,
    backgroundColor: "#fff",
    marginTop: 2,
  },
  foodPromoActionText: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodPromoArt: {
    width: 90,
    alignItems: "center",
    justifyContent: "center",
    marginRight: -4,
    transform: [{ rotate: "-7deg" }],
    borderRadius: 32,
    backgroundColor: flashDesign.color.food,
  },
  foodPromoArtDot: {
    position: "absolute",
    right: -18,
    bottom: -20,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(255,255,255,.18)",
  },
  foodSearchButton: {
    minHeight: 54,
    borderRadius: 18,
    paddingLeft: 15,
    paddingRight: 7,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  foodSearchPlaceholder: { color: flashDesign.color.muted, flex: 1, fontSize: 13 },
  foodSearchFilter: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.ink,
  },
  foodSearchInput: { color: "#252128", flex: 1, minHeight: 46 },
  foodSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  foodSectionTitle: {
    color: flashDesign.color.ink,
    fontSize: flashDesign.type.section,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  foodSeeAll: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "800" },
  foodCategoryRail: { gap: 10, paddingVertical: 4, paddingRight: 4 },
  foodCategoryItem: { width: 76, alignItems: "center", gap: 7 },
  foodCategoryArt: {
    width: 68,
    height: 68,
    borderRadius: 23,
    backgroundColor: flashDesign.color.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCategoryArtActive: {
    borderColor: flashDesign.color.food,
    borderWidth: 2,
    shadowColor: flashDesign.color.food,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 2,
  },
  foodCategoryImage: { width: 60, height: 60, borderRadius: 19 },
  foodCategoryName: {
    minHeight: 28,
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  foodCategoryNameActive: { color: flashDesign.color.foodDeep, fontWeight: "900" },
  foodFavoriteRail: { gap: 12, paddingRight: 4, paddingBottom: 2 },
  foodFavoriteCard: {
    width: 166,
    padding: 7,
    borderRadius: 19,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodFavoriteImage: { height: 94, padding: 7, alignItems: "flex-end" },
  foodFavoriteImageStyle: { borderRadius: 14 },
  foodFavoriteEta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.94)",
  },
  foodFavoriteEtaText: { color: flashDesign.color.ink, fontSize: 9, fontWeight: "900" },
  foodFavoriteName: {
    color: flashDesign.color.ink,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 7,
    paddingHorizontal: 2,
  },
  foodFavoriteMeta: {
    color: flashDesign.color.muted,
    fontSize: 10,
    marginTop: 2,
    paddingHorizontal: 2,
    paddingBottom: 2,
  },
  foodOffer: {
    minHeight: 112,
    borderRadius: 22,
    padding: 17,
    backgroundColor: "#ffad25",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  foodOfferKicker: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  foodOfferTitle: {
    color: "#fff",
    fontSize: 23,
    fontWeight: "900",
    marginTop: 3,
  },
  foodOfferCopy: { color: "rgba(255,255,255,.85)", marginTop: 4 },
  foodPopularRail: { gap: 12, paddingBottom: 3 },
  foodPopularCard: {
    width: 150,
    padding: 8,
    borderRadius: 18,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eee9ec",
  },
  foodPopularImage: {
    height: 104,
    borderRadius: 14,
    padding: 8,
    alignItems: "flex-end",
  },
  foodPopularImageStyle: { borderRadius: 14 },
  foodPopularEta: {
    color: "#252128",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
  },
  foodPopularName: { color: "#252128", fontWeight: "900", marginTop: 8 },
  foodPopularRestaurant: { color: "#88838a", fontSize: 11, marginTop: 2 },
  foodMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
  },
  foodRating: { color: "#ff6a21", fontWeight: "900" },
  foodMetaItem: { flexDirection: "row", alignItems: "center", gap: 4 },
  foodMetaText: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "700" },
  foodMetaDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: "#C3BDC7" },
  foodHeart: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: flashDesign.color.ink,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 2,
  },
  foodPageHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 50,
  },
  foodPageHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  foodBack: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 16,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    alignItems: "center",
    justifyContent: "center",
  },
  foodPageTitle: {
    color: flashDesign.color.ink,
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  foodPageSubtitle: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "700" },
  foodSearchClear: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surfaceMuted,
  },
  foodSearchCategoryRail: { gap: 10, paddingRight: 4, paddingBottom: 2 },
  foodSearchCategoryCard: {
    width: 126,
    padding: 8,
    borderRadius: 18,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchCategoryImage: { width: "100%", height: 74, borderRadius: 13 },
  foodSearchCategoryImageFallback: {
    width: "100%",
    height: 74,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodSearchCategoryName: {
    minHeight: 30,
    color: flashDesign.color.ink,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "900",
    marginTop: 7,
  },
  foodSearchCategoryCount: {
    color: flashDesign.color.muted,
    fontSize: 9,
    fontWeight: "700",
    marginTop: 2,
  },
  foodSearchSkeletonList: { gap: 10 },
  foodSearchSkeletonCard: {
    minHeight: 110,
    flexDirection: "row",
    gap: 12,
    padding: 9,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchSkeletonImage: { width: 98, borderRadius: 14, backgroundColor: "#E9E5EC" },
  foodSearchSkeletonCopy: { flex: 1, justifyContent: "center", gap: 9 },
  foodSearchSkeletonTitle: {
    width: "72%",
    height: 14,
    borderRadius: 7,
    backgroundColor: "#E6E1E9",
  },
  foodSearchSkeletonLine: { width: "92%", height: 10, borderRadius: 5, backgroundColor: "#EEEAF0" },
  foodSearchSkeletonShort: {
    width: "52%",
    height: 10,
    borderRadius: 5,
    backgroundColor: "#EEEAF0",
  },
  foodSearchState: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    padding: 22,
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodSearchStateIcon: {
    width: 54,
    height: 54,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodSearchStateTitle: { color: flashDesign.color.ink, fontSize: 17, fontWeight: "900" },
  foodSearchStateCopy: {
    maxWidth: 270,
    color: flashDesign.color.inkSoft,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  foodSearchRetry: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    borderRadius: 13,
    backgroundColor: flashDesign.color.ink,
    marginTop: 2,
  },
  foodSearchRetryText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  foodSearchResultCard: {
    overflow: "hidden",
    borderRadius: 21,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 15,
    elevation: 2,
  },
  foodSearchResultImage: { height: 148, padding: 10, alignItems: "flex-end" },
  foodSearchResultEta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(255,255,255,.95)",
  },
  foodSearchResultEtaText: { color: flashDesign.color.ink, fontSize: 10, fontWeight: "900" },
  foodSearchResultBody: { gap: 6, padding: 13 },
  foodSearchResultHeading: { flexDirection: "row", alignItems: "center", gap: 8 },
  foodSearchResultName: { flex: 1, color: flashDesign.color.ink, fontSize: 16, fontWeight: "900" },
  foodSearchResultCuisine: { color: flashDesign.color.inkSoft, fontSize: 11 },
  foodSearchResultMeta: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  foodSearchResultMetaText: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "700" },
  foodSearchResult: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 10,
  },
  foodResultImage: { width: 70, height: 62, borderRadius: 13 },
  foodRestaurantHero: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: flashDesign.radius.surface,
    overflow: "hidden",
    padding: 13,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  foodRestaurantHeroImage: { borderRadius: flashDesign.radius.surface },
  foodFloatingButton: {
    width: flashDesign.control.touch,
    height: flashDesign.control.touch,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,.96)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: flashDesign.color.ink,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    elevation: 2,
  },
  foodRestaurantInfo: {
    backgroundColor: flashDesign.color.surface,
    borderRadius: flashDesign.radius.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 17,
    marginTop: -26,
    marginHorizontal: 10,
    gap: 9,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 4,
  },
  foodRestaurantStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  foodRestaurantOpenBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: flashDesign.color.successSoft,
  },
  foodRestaurantOpenDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: flashDesign.color.shipment,
  },
  foodRestaurantOpenText: {
    color: flashDesign.color.shipment,
    fontSize: 9,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  foodRestaurantOfferBadge: {
    maxWidth: "58%",
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodRestaurantTitle: {
    color: flashDesign.color.ink,
    fontSize: 23,
    lineHeight: 28,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  foodRestaurantCuisine: { color: flashDesign.color.inkSoft, fontSize: 11, lineHeight: 16 },
  foodRestaurantFacts: { flexDirection: "row", gap: 8, paddingTop: 3 },
  foodRestaurantFact: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    padding: 8,
    borderRadius: 14,
    backgroundColor: flashDesign.color.canvas,
  },
  foodRestaurantFactIcon: {
    width: 30,
    height: 30,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
  },
  foodRestaurantFactValue: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodRestaurantFactLabel: { color: flashDesign.color.muted, fontSize: 8, marginTop: 1 },
  foodMenuTabs: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 2,
    paddingRight: 4,
  },
  foodMenuTabButton: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodMenuTabButtonActive: {
    backgroundColor: flashDesign.color.ink,
    borderColor: flashDesign.color.ink,
  },
  foodMenuTab: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "800" },
  foodMenuTabActive: {
    color: "#fff",
    fontWeight: "900",
  },
  foodProductCard: {
    minHeight: 122,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: flashDesign.color.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 9,
  },
  foodProductImage: {
    width: 104,
    height: 104,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  foodProductImageStyle: { borderRadius: 16 },
  foodProductUnavailable: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(23,19,28,.78)",
  },
  foodProductUnavailableText: { color: "#fff", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  foodProductHeading: { flexDirection: "row", alignItems: "flex-start", gap: 6 },
  foodProductName: {
    flex: 1,
    color: flashDesign.color.ink,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  foodProductDescription: { color: flashDesign.color.inkSoft, fontSize: 10, lineHeight: 14 },
  foodProductPrice: { color: flashDesign.color.foodDeep, fontWeight: "900", marginTop: 3 },
  foodAddButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: flashDesign.color.food,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-end",
  },
  foodAddButtonDisabled: { backgroundColor: "#C8C2CB" },
  foodStickyCart: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: "#ff6a21",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    gap: 12,
  },
  foodStickyCount: {
    width: 30,
    height: 30,
    borderRadius: 10,
    paddingTop: 5,
    textAlign: "center",
    color: "#ff6a21",
    backgroundColor: "#fff",
    fontWeight: "900",
    overflow: "hidden",
  },
  foodStickyLabel: { color: "#fff", fontWeight: "900", flex: 1 },
  foodStickyPrice: { color: "#fff", fontWeight: "900" },
  foodCartMerchant: {
    minHeight: 86,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 10,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCartMerchantImage: { width: 66, height: 66, borderRadius: 16 },
  foodCartMerchantEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1,
  },
  foodCartMerchantName: {
    color: flashDesign.color.ink,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 2,
  },
  foodCartMerchantMeta: { color: flashDesign.color.inkSoft, fontSize: 10, marginTop: 3 },
  foodCartLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: flashDesign.color.surface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 11,
  },
  foodCartLineIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartLineName: { color: flashDesign.color.ink, fontSize: 13, fontWeight: "900" },
  foodCartLineMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 2 },
  foodCartLineNote: {
    color: flashDesign.color.inkSoft,
    fontSize: 9,
    lineHeight: 13,
    fontStyle: "italic",
    marginTop: 2,
  },
  foodQuantity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 15,
    backgroundColor: flashDesign.color.canvas,
    padding: 4,
  },
  foodQuantityButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodQuantityButtonAdd: {
    backgroundColor: flashDesign.color.food,
    borderColor: flashDesign.color.food,
  },
  foodQuantityValue: {
    minWidth: 18,
    color: flashDesign.color.ink,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  foodTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  foodCartOptionList: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCartOption: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 11,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
    backgroundColor: flashDesign.color.surface,
  },
  foodCartOptionSelected: { backgroundColor: "#FFF9F5" },
  foodCartOptionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartOptionIconSelected: { backgroundColor: flashDesign.color.food },
  foodCartPaymentIcon: { backgroundColor: "#EEE7FF" },
  foodCartPaymentIconSelected: { backgroundColor: flashDesign.color.brand },
  foodCartOptionTitleRow: { flexDirection: "row", alignItems: "center", gap: 7, flexWrap: "wrap" },
  foodCartOptionTitle: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodCartOptionMeta: {
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
  foodCartDefaultBadge: {
    color: flashDesign.color.foodDeep,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.5,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCartMissingOption: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    backgroundColor: "#FFF4F2",
  },
  foodCouponField: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingLeft: 8,
    paddingRight: 7,
    borderRadius: 18,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCouponIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCouponInput: {
    flex: 1,
    minHeight: 50,
    color: flashDesign.color.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  foodCartTotalCard: {
    minHeight: 92,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    padding: 15,
    borderRadius: 20,
    backgroundColor: flashDesign.color.ink,
  },
  foodCartTotalLabel: { color: "#FFD4BF", fontSize: 9, fontWeight: "900", letterSpacing: 1 },
  foodCartTotalHelp: {
    maxWidth: 210,
    color: "rgba(255,255,255,.62)",
    fontSize: 9,
    lineHeight: 13,
    marginTop: 5,
  },
  foodCartTotalValue: { color: "#fff", fontSize: 22, fontWeight: "900" },
  foodCheckoutPrimary: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 15,
    borderRadius: 17,
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 3,
  },
  foodCheckoutPrimaryText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  foodEmpty: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    backgroundColor: flashDesign.color.surface,
    borderRadius: flashDesign.radius.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    padding: 24,
  },
  foodEmptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodEmptyTitle: {
    color: flashDesign.color.ink,
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
  },
  foodEmptyCopy: {
    maxWidth: 280,
    color: flashDesign.color.inkSoft,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  foodEmptyAction: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: flashDesign.color.ink,
  },
  foodEmptyActionText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  foodBottomNav: {
    flexDirection: "row",
    minHeight: 68,
    backgroundColor: "#fff",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#eee9ec",
    marginHorizontal: 14,
    marginBottom: 8,
    paddingHorizontal: 6,
    shadowColor: "#241a28",
    shadowOpacity: 0.1,
    shadowRadius: 14,
  },
  foodBottomItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  foodBottomLabel: { color: "#9c989f", fontSize: 10, fontWeight: "700" },
  foodBottomLabelActive: { color: "#ff6a21" },
  shareAction: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 13,
    backgroundColor: "#fff7f2",
    borderWidth: 1,
    borderColor: "#ffe0cf",
  },
  shareActionText: { color: "#ff6a21", fontSize: 12, fontWeight: "900" },
  activityHeading: { paddingVertical: 10, gap: 4 },
  customerAccountHeading: {
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  customerLogoutButton: {
    minHeight: 44,
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#dedbe1",
    backgroundColor: "#fff",
  },
  customerLogoutText: { color: "#27242a", fontSize: 13, fontWeight: "900" },
  activityCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  activityIconFood: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#ff6a21",
    alignItems: "center",
    justifyContent: "center",
  },
  activityIconRide: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionSectionTitle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 8,
  },
  substitutionCount: {
    minWidth: 30,
    height: 30,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: "#ff6a21",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionCountText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  substitutionCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 15,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ffd8c4",
    shadowColor: "#7c3cff",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  substitutionAlert: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  substitutionContent: { flex: 1, gap: 10 },
  substitutionEyebrow: {
    color: "#ff6a21",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  substitutionTitle: { color: "#211d24", fontSize: 18, fontWeight: "900" },
  substitutionArrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 11,
    borderRadius: 16,
    backgroundColor: "#f8f5fb",
  },
  substitutionProduct: { flex: 1, gap: 2 },
  substitutionPrice: { color: "#211d24", fontSize: 13, fontWeight: "900" },
  substitutionReason: { color: "#736d77", fontSize: 12, lineHeight: 17 },
  substitutionRefund: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    padding: 10,
    borderRadius: 13,
    backgroundColor: "#e6f8ef",
  },
  substitutionRefundText: { flex: 1, color: "#087a50", fontSize: 12, fontWeight: "800" },
  substitutionActions: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  substitutionReject: {
    flex: 1,
    minHeight: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ddd6e2",
    backgroundColor: "#fff",
  },
  substitutionRejectText: { color: "#554f59", fontSize: 12, fontWeight: "900" },
  substitutionAccept: {
    flex: 1.35,
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    backgroundColor: "#ff6a21",
  },
  substitutionAcceptText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  reportIssueButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "#fff4f1",
    borderWidth: 1,
    borderColor: "#ffd9d1",
  },
  reportIssueText: { flex: 1, color: "#a63e2c", fontSize: 12, fontWeight: "900" },
  issueModalBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(24,18,27,.52)",
  },
  issueModalSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "90%",
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 28,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  issueModalHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 4,
    backgroundColor: "#ddd6e0",
  },
  issueModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  issueModalClose: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: "#f5f1f6",
  },
  issueCategoryRail: { gap: 8, paddingVertical: 2 },
  issueCategoryPill: {
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 13,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#e4dde7",
    backgroundColor: "#fff",
  },
  issueCategoryPillActive: { borderColor: "#ff6a21", backgroundColor: "#fff3ec" },
  issueCategoryText: { color: "#706872", fontSize: 11, fontWeight: "800" },
  issueCategoryTextActive: { color: "#d84d11" },
  issueFieldLabel: { color: "#302a32", fontSize: 12, fontWeight: "900" },
  issueDescriptionInput: { minHeight: 96, textAlignVertical: "top", paddingTop: 12 },
  issueMoneyInput: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#e4dde7",
    borderRadius: 15,
    backgroundColor: "#faf8fb",
  },
  issueMoneyPrefix: { color: "#211d24", fontSize: 20, fontWeight: "900" },
  issueMoneyTextInput: {
    flex: 1,
    paddingHorizontal: 8,
    color: "#211d24",
    fontSize: 20,
    fontWeight: "900",
  },
  issueSecurityNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 11,
    borderRadius: 14,
    backgroundColor: "#eaf8f1",
  },
  issueSecurityText: { flex: 1, color: "#087a50", fontSize: 11, lineHeight: 16, fontWeight: "700" },
  issueSubmitButton: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 16,
    backgroundColor: "#ff6a21",
  },
  issueSubmitText: { color: "#fff", fontSize: 13, fontWeight: "900" },
  accountCard: {
    alignItems: "center",
    gap: 8,
    padding: 22,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  accountAvatar: {
    width: 74,
    height: 74,
    borderRadius: 28,
    backgroundColor: "#efe7ff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 5,
  },
  accountInitial: { color: "#7c3cff", fontSize: 30, fontWeight: "900" },
  accountDetail: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    borderRadius: 15,
    backgroundColor: "#f7f5f8",
    marginTop: 5,
  },
  addressBookCard: {
    gap: 14,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe7ed",
  },
  addressBookHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  savedAddressRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 11,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0edf2",
  },
  savedAddressIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0eaff",
  },
  savedAddressIconDefault: { backgroundColor: "#7c3cff" },
  savedAddressCopy: { flex: 1, minWidth: 180, gap: 3 },
  savedAddressTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  addressValidationStatus: { flexDirection: "row", alignItems: "center", gap: 5, marginTop: 3 },
  addressValidationText: { color: "#087a50", fontSize: 11, fontWeight: "800" },
  addressValidationTextWarning: { color: "#a15c00" },
  defaultAddressBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    color: "#6d35dc",
    backgroundColor: "#efe7ff",
    borderRadius: 999,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  savedAddressActions: { flexDirection: "row", alignItems: "center", gap: 13 },
  newAddressForm: { gap: 11, paddingTop: 5 },
  addressMatchList: {
    gap: 7,
    padding: 10,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e8e0f4",
    backgroundColor: "#faf8fc",
  },
  addressMatchHint: { color: "#6f6872", fontSize: 11, fontWeight: "700" },
  addressMatchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#fff",
  },
  addressMatchIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0eaff",
  },
  addressMatchCopy: { flex: 1, gap: 2 },
  addressMatchLabel: { color: "#2f2a32", fontSize: 13, fontWeight: "800" },
  addressMatchMeta: { color: "#8a838d", fontSize: 10, fontWeight: "600" },
  addressSelectedNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#eaf8f1",
  },
  addressSelectedText: { flex: 1, color: "#087a50", fontSize: 11, fontWeight: "700" },
  paymentMethodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#f0edf2",
  },
  paymentBrandRail: { gap: 8, paddingVertical: 2 },
  paymentCompactFields: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  paymentCompactInput: { flex: 1, minWidth: 140 },
  notificationBell: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 13,
    borderRadius: 17,
    backgroundColor: "#faf8fb",
  },
  notificationUnread: { backgroundColor: "#f3edff", borderWidth: 1, borderColor: "#dfd0ff" },
  notificationStatusDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: "#7c3cff",
    marginTop: 6,
  },
  notificationTime: { fontSize: 11, color: "#9c989f", marginTop: 3 },
  notificationNew: { fontSize: 9, fontWeight: "900", color: "#7c3cff", letterSpacing: 0.8 },
  notificationEmpty: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#eefaf5",
  },
  preferenceGroup: { gap: 9, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#f0edf2" },
  preferenceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  preferenceSwitch: {
    width: 48,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#ded9e1",
    padding: 3,
  },
  preferenceSwitchActive: { backgroundColor: "#7c3cff" },
  preferenceKnob: { width: 22, height: 22, borderRadius: 11, backgroundColor: "#fff" },
  preferenceKnobActive: { alignSelf: "flex-end" },
  supportTicketCard: {
    gap: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#faf8fb",
    borderWidth: 1,
    borderColor: "#ece7ef",
  },
  supportTicketHeader: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  supportSla: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    color: "#087a50",
    backgroundColor: "#e5f8f0",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 9,
  },
  supportSlaLate: { color: "#b3302c", backgroundColor: "#ffe9e7" },
  supportMessages: { gap: 7 },
  supportMessage: { maxWidth: "88%", paddingHorizontal: 11, paddingVertical: 8, borderRadius: 14 },
  supportMessageOwn: { alignSelf: "flex-end", backgroundColor: "#7c3cff" },
  supportMessageStaff: { alignSelf: "flex-start", backgroundColor: "#ece8ef" },
  supportMessageText: { fontSize: 13, color: "#262128" },
  supportMessageTextOwn: { color: "#fff" },
  supportMessageTime: { fontSize: 9, color: "#9c989f", marginTop: 3 },
  supportReplyRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  supportReplyInput: { flex: 1 },
  supportSendButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  complianceCard: {
    gap: 13,
    padding: 17,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e4ec",
  },
  deliveryProofCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#f7f1ff",
    borderWidth: 1,
    borderColor: "#e3d3ff",
  },
  deliveryProofIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7c3cff",
  },
  deliveryEvidenceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#e8f7f0",
  },
  deliveryEvidenceBadgeText: { fontSize: 12, fontWeight: "800", color: "#087a50" },
  productCustomizerBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(20,16,24,.56)",
  },
  productCustomizerSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "92%",
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: 28,
    gap: 14,
    borderTopLeftRadius: flashDesign.radius.sheet,
    borderTopRightRadius: flashDesign.radius.sheet,
    backgroundColor: flashDesign.color.canvas,
  },
  productCustomizerHandle: {
    alignSelf: "center",
    width: 42,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#D5CFD8",
  },
  productCustomizerHeader: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  productCustomizerEyebrow: {
    color: flashDesign.color.foodDeep,
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
  },
  productCustomizerTitle: {
    color: flashDesign.color.ink,
    fontSize: 22,
    lineHeight: 27,
    fontWeight: "900",
    letterSpacing: -0.4,
    marginTop: 2,
  },
  productCustomizerRestaurant: { color: flashDesign.color.inkSoft, fontSize: 10, marginTop: 3 },
  productCustomizerContent: { gap: 13, paddingBottom: 6 },
  productCustomizerSummary: {
    minHeight: 100,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 10,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  productCustomizerImage: { width: 82, height: 82, borderRadius: 16 },
  productCustomizerSummaryPrice: {
    color: flashDesign.color.foodDeep,
    fontSize: 17,
    fontWeight: "900",
  },
  productCustomizerSummaryDescription: {
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 15,
    marginTop: 4,
  },
  productCustomizerWarningIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.7)",
  },
  foodCustomizerGroup: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCustomizerGroupHeader: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 13,
    backgroundColor: "#FBF9FC",
  },
  foodCustomizerGroupTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
  },
  foodCustomizerGroupTitle: { color: flashDesign.color.ink, fontSize: 14, fontWeight: "900" },
  foodCustomizerGroupMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCustomizerRequirement: {
    color: flashDesign.color.inkSoft,
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.surfaceMuted,
  },
  foodCustomizerRequirementRequired: {
    color: flashDesign.color.foodDeep,
    backgroundColor: flashDesign.color.warningSoft,
  },
  dietaryBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  dietaryBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#e9f8ef",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  dietaryBadgeText: { color: "#087a50", fontSize: 12, fontWeight: "800" },
  dietaryPreferenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 8,
    marginBottom: 14,
  },
  dietaryPreferenceChip: {
    borderWidth: 1,
    borderColor: "#ddd9e1",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  dietaryPreferenceChipActive: { backgroundColor: "#e9f8ef", borderColor: "#8ed5aa" },
  dietaryAllergenChipActive: { backgroundColor: "#fff0e6", borderColor: "#ffb47b" },
  dietaryPreferenceText: { fontSize: 12, fontWeight: "800", color: "#6a6570" },
  dietaryPreferenceTextActive: { color: "#087a50" },
  dietaryAllergenTextActive: { color: "#a3480a" },
  dietarySafetyNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "#fff8eb",
    borderRadius: 12,
    padding: 10,
    marginTop: 10,
  },
  dietaryFilterBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#e9f8ef",
    borderRadius: 12,
    padding: 10,
  },
  searchStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    padding: 22,
    backgroundColor: "#f8f7f9",
    borderRadius: 16,
  },
  searchMatchText: { fontSize: 11, color: "#8a6578", marginTop: 3 },
  searchMoreButton: {
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffb992",
    borderRadius: 14,
    padding: 13,
  },
  searchMoreText: { color: "#d64c0b", fontWeight: "900" },
  orderConfirmationCard: {
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#FFD0AF",
    borderRadius: flashDesign.radius.surface,
    padding: 22,
    marginBottom: 4,
  },
  orderConfirmationIcon: {
    width: 58,
    height: 58,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 3,
  },
  orderConfirmationEyebrow: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.4,
    color: flashDesign.color.foodDeep,
    marginTop: 3,
  },
  orderConfirmationTitle: {
    color: flashDesign.color.ink,
    fontSize: 21,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: -0.4,
  },
  orderConfirmationCopy: {
    maxWidth: 290,
    color: flashDesign.color.inkSoft,
    fontSize: 11,
    lineHeight: 16,
    textAlign: "center",
  },
  orderConfirmationTotal: {
    color: flashDesign.color.ink,
    fontSize: 25,
    fontWeight: "900",
    marginVertical: 3,
  },
  orderConfirmationAction: {
    width: "100%",
    minHeight: 50,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: flashDesign.color.ink,
    borderRadius: 16,
    padding: 13,
    marginTop: 6,
  },
  orderConfirmationActionText: { color: "#fff", fontWeight: "900" },
  foodActiveOrderCard: {
    gap: 12,
    padding: 14,
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  foodActiveOrderHeader: { flexDirection: "row", alignItems: "center", gap: 10 },
  foodActiveOrderIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.food,
  },
  foodActiveOrderEyebrow: {
    color: flashDesign.color.muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  foodActiveOrderStatus: {
    color: flashDesign.color.ink,
    fontSize: 15,
    fontWeight: "900",
    marginTop: 2,
  },
  foodActiveOrderEta: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodActiveOrderDestination: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
    borderRadius: 15,
    backgroundColor: flashDesign.color.canvas,
  },
  foodActiveOrderDestinationText: {
    flex: 1,
    color: flashDesign.color.inkSoft,
    fontSize: 10,
    lineHeight: 14,
  },
  foodActiveOrderTotal: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodActiveOrderActions: { flexDirection: "row", gap: 8 },
  foodActiveOrderSecondary: {
    flex: 1,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#FFD7C2",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodActiveOrderSecondaryText: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  foodActiveOrderPrimary: {
    flex: 1.3,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 14,
    backgroundColor: flashDesign.color.ink,
  },
  foodActiveOrderPrimaryText: { color: "#fff", fontSize: 11, fontWeight: "900" },
  foodActiveOrderCancel: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 11,
    borderTopWidth: 1,
    borderTopColor: flashDesign.color.line,
  },
  foodActiveOrderCancelText: { color: flashDesign.color.danger, fontSize: 10, fontWeight: "800" },
  reorderButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    backgroundColor: "#ff6a21",
    borderRadius: 13,
    padding: 12,
    marginTop: 12,
  },
  reorderButtonText: { color: "#fff", fontWeight: "900" },
  trackingBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(20,15,24,.48)",
  },
  trackingSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "92%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 18,
    gap: 15,
  },
  trackingHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  trackingMap: { height: 260, borderRadius: 20, overflow: "hidden", backgroundColor: "#e8e4ed" },
  nativeMapEmpty: {
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 26,
    borderWidth: 1,
    borderColor: "#ded9e3",
  },
  nativeMapEmptyTitle: { color: "#17131c", fontSize: 14, fontWeight: "900", textAlign: "center" },
  nativeMapEmptyText: {
    color: "#716a76",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 16,
    textAlign: "center",
  },
  trackingMapCaption: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    backgroundColor: "rgba(255,255,255,.94)",
    borderRadius: 13,
    padding: 10,
  },
  trackingMapCaptionTitle: { fontSize: 13, fontWeight: "900", color: "#252128" },
  trackingMapCaptionText: { fontSize: 11, color: "#68616c", marginTop: 2 },
  trackingStatus: { gap: 4 },
  trackingProgress: { marginTop: 12, gap: 7 },
  trackingStage: { flexDirection: "row", alignItems: "center", gap: 9 },
  trackingStageDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#e3dfe6",
    alignItems: "center",
    justifyContent: "center",
  },
  trackingStageText: { fontSize: 12, color: "#918b95" },
  trackingStageTextActive: { fontWeight: "900", color: "#252128" },
  shipmentProtectionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded9e2",
    borderRadius: 15,
    padding: 11,
    backgroundColor: "#fff",
  },
  shipmentProtectionCardActive: { borderColor: "#73c894", backgroundColor: "#eefaf2" },
  shipmentProtectionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#087a50",
    alignItems: "center",
    justifyContent: "center",
  },
  shipmentOptionRail: { gap: 9, paddingVertical: 2 },
  shipmentOptionCard: {
    minWidth: 92,
    minHeight: 70,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#ded9e2",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 12,
  },
  shipmentOptionCardActive: { backgroundColor: "#7c3cff", borderColor: "#7c3cff" },
  shipmentOptionText: { color: "#5c5362", fontSize: 12, fontWeight: "800" },
  shipmentOptionTextActive: { color: "#fff", fontSize: 12, fontWeight: "900" },
  shipmentOptionMeta: { color: "#918898", fontSize: 9, fontWeight: "700" },
  shipmentOptionMetaActive: { color: "#e5d9ff", fontSize: 9, fontWeight: "700" },
  errorText: { color: "#b42318", fontSize: 12, fontWeight: "700" },
  shipmentSlaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  shipmentSlaCard: {
    width: "48%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ded9e2",
    backgroundColor: "#fff",
    padding: 12,
  },
  shipmentSlaCardActive: { backgroundColor: "#17131c", borderColor: "#17131c" },
  shipmentSlaTitle: { color: "#231d27", fontWeight: "900" },
  shipmentSlaTitleActive: { color: "#fff", fontWeight: "900" },
  shipmentSlaCaption: { color: "#807785", fontSize: 11, marginTop: 2 },
  shipmentSlaCaptionActive: { color: "#d7cedc", fontSize: 11, marginTop: 2 },
  protectionQuoteText: { fontSize: 12, fontWeight: "800", color: "#087a50", marginTop: 5 },
  returnStatusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#f2edff",
    borderRadius: 12,
    padding: 11,
    marginTop: 10,
  },
  allergenWarning: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    backgroundColor: "#fff4df",
    borderWidth: 1,
    borderColor: "#ffd69a",
    borderRadius: 14,
    padding: 12,
  },
  allergenWarningTitle: { fontSize: 13, fontWeight: "900", color: "#7c3b00" },
  allergenWarningText: { fontSize: 11, lineHeight: 16, color: "#7c4c20" },
  modifierCounter: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  modifierRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    borderTopWidth: 1,
    borderTopColor: flashDesign.color.line,
  },
  modifierRowSelected: { backgroundColor: "#FFF9F5" },
  modifierRowBlocked: { opacity: 0.42 },
  modifierControl: {
    width: 23,
    height: 23,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#C8C1CC",
    backgroundColor: flashDesign.color.surface,
  },
  modifierControlSelected: {
    backgroundColor: flashDesign.color.food,
    borderColor: flashDesign.color.food,
  },
  modifierName: { flex: 1, color: flashDesign.color.ink, fontSize: 12, fontWeight: "800" },
  modifierPrice: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "800" },
  foodCustomizerNoteSection: {
    gap: 10,
    padding: 13,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCustomizerNoteHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  foodCustomizerNoteCount: { color: flashDesign.color.muted, fontSize: 9, fontWeight: "800" },
  productNote: {
    minHeight: 92,
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    backgroundColor: flashDesign.color.canvas,
    color: flashDesign.color.ink,
    fontSize: 12,
    textAlignVertical: "top",
  },
  productCustomizerAction: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 18,
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 3,
  },
  productCustomizerActionCount: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.18)",
  },
  productCustomizerActionCountText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  productCustomizerActionText: { flex: 1, color: "#fff", fontSize: 13, fontWeight: "900" },
  productCustomizerActionPrice: { color: "#fff", fontSize: 13, fontWeight: "900" },
  foodCheckoutHero: {
    minHeight: 190,
    gap: 8,
    padding: 18,
    borderRadius: flashDesign.radius.surface,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 22,
    elevation: 4,
  },
  foodCheckoutHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  foodCheckoutVerified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(8,122,80,.25)",
  },
  foodCheckoutVerifiedText: {
    color: "#BDF3D7",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  foodCheckoutExpiry: { color: "rgba(255,255,255,.6)", fontSize: 9, fontWeight: "800" },
  foodCheckoutMerchant: {
    color: "#fff",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "900",
    letterSpacing: -0.5,
    marginTop: 7,
  },
  foodCheckoutEta: { color: "rgba(255,255,255,.72)", fontSize: 12 },
  foodCheckoutHeroFacts: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    marginTop: "auto",
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.12)",
  },
  foodCheckoutHeroDivider: { width: 1, height: 30, backgroundColor: "rgba(255,255,255,.16)" },
  foodCheckoutHeroFactLabel: {
    color: "rgba(255,255,255,.52)",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  foodCheckoutHeroFactValue: { color: "#fff", fontSize: 11, fontWeight: "900", marginTop: 3 },
  foodCheckoutInfoList: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCheckoutInfoCard: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
  },
  foodCheckoutInfoIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  foodCheckoutInfoTitle: {
    color: flashDesign.color.muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  foodCheckoutInfoValue: {
    color: flashDesign.color.ink,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    marginTop: 2,
  },
  foodCheckoutInfoMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCheckoutItems: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  checkoutItem: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
  },
  foodCheckoutItemQuantity: {
    minWidth: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCheckoutItemQuantityText: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  foodCheckoutItemName: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodCheckoutItemMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCheckoutItemNote: {
    color: flashDesign.color.inkSoft,
    fontSize: 9,
    lineHeight: 13,
    fontStyle: "italic",
    marginTop: 3,
  },
  foodCheckoutItemPrice: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodCheckoutTotals: {
    gap: 2,
    padding: 15,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCheckoutTotalLabel: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "700" },
  foodCheckoutTotalAmount: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodCheckoutDiscountLabel: { color: flashDesign.color.shipment, fontSize: 11, fontWeight: "800" },
  foodCheckoutDiscountAmount: {
    color: flashDesign.color.shipment,
    fontSize: 11,
    fontWeight: "900",
  },
  foodCheckoutTotalDivider: {
    height: 1,
    backgroundColor: flashDesign.color.line,
    marginVertical: 4,
  },
  foodCheckoutGrandLabel: { color: flashDesign.color.ink, fontSize: 17, fontWeight: "900" },
  foodCheckoutGrandAmount: { color: flashDesign.color.ink, fontSize: 20, fontWeight: "900" },
  foodCheckoutSecurity: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 17,
    backgroundColor: flashDesign.color.successSoft,
  },
  foodCheckoutSecurityIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
  },
  foodCheckoutSecurityText: {
    flex: 1,
    color: flashDesign.color.shipment,
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "700",
  },
  foodCheckoutRefresh: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FFD0B8",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCheckoutRefreshText: { color: flashDesign.color.foodDeep, fontSize: 12, fontWeight: "900" },
  proofCameraButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 13,
    backgroundColor: "#18151d",
  },
  complianceHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  complianceBadge: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    color: "#7c3cff",
    backgroundColor: "#efe7ff",
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 10,
  },
  complianceBadgeApproved: { color: "#087a50", backgroundColor: "#e5f8f0" },
  complianceBadgeRejected: { color: "#b3302c", backgroundColor: "#ffe9e7" },
  complianceDocuments: { gap: 8 },
  complianceDocumentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 11,
    borderRadius: 15,
    backgroundColor: "#faf8fb",
  },
  complianceRejection: { fontSize: 11, color: "#b3302c", fontWeight: "700" },
  newAddressFields: { flexDirection: "row", gap: 8 },
  addressLabelInput: { width: 92 },
  addressTextInput: { flex: 1 },
  primaryButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 15,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
  },
  primaryButtonText: { color: "#fff", fontWeight: "900" },
  disabledButton: { opacity: 0.45 },

  // Propina en el checkout (GTM-001). Los objetivos táctiles son de 44px: es la
  // única decisión del checkout que se toma con el pulgar sobre una lista de
  // montos parecidos, y ahí un objetivo chico hace dejar la propina equivocada.
  propinaSelector: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#efe9f0",
    padding: 16,
    gap: 8,
  },
  propinaOpciones: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  propinaOpcion: {
    minHeight: 44,
    minWidth: 78,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    alignItems: "center",
    justifyContent: "center",
  },
  // Se marca con borde y fondo, no sólo con color: un cambio de color solo no lo
  // distingue quien no separa esos dos tonos.
  propinaOpcionActiva: { borderColor: "#ff6a21", backgroundColor: "rgba(255,106,33,0.10)" },
  propinaOpcionTexto: { color: "#27242a", fontWeight: "700" },
  propinaOpcionMonto: { color: "#6c6870", fontSize: 12 },
  propinaLibre: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  propinaInput: {
    minHeight: 44,
    width: 120,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    textAlign: "right",
    color: "#27242a",
  },

  // Suscripción de Flash (GTM-001). Espeja `accountCard` para que la pantalla de
  // cuenta no cambie de idioma visual a mitad de scroll.
  suscripcionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#efe9f0",
    padding: 18,
    gap: 10,
  },
  suscripcionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  suscripcionPrecio: { fontSize: 20, fontWeight: "700", color: "#27242a" },
  suscripcionChip: {
    backgroundColor: "rgba(22,163,74,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  // Cancelada pero vigente: ámbar y no rojo, porque los beneficios siguen y un
  // rojo diría que ya se perdieron.
  suscripcionChipVence: {
    backgroundColor: "rgba(217,119,6,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  suscripcionChipText: { fontSize: 12, color: "#27242a" },
  suscripcionAviso: { fontSize: 13, color: "#b45309" },
  suscripcionAlta: {
    backgroundColor: "#ff6a21",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  suscripcionAltaText: { color: "#ffffff", fontWeight: "700" },
  // La baja es secundaria, no destructiva: no se esconde ni se pinta de peligro.
  suscripcionBaja: {
    borderWidth: 1,
    borderColor: "#efe9f0",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  suscripcionBajaText: { color: "#27242a", fontWeight: "600" },
  suscripcionOk: { fontSize: 13, color: "#087a50" },
  suscripcionError: { fontSize: 13, color: "#b91c1c" },

  // Pedidos grupales (GTM-001). Reutiliza la tarjeta de suscripción para que la
  // pantalla no cambie de idioma visual a mitad de scroll.
  grupoSumarse: { flexDirection: "row", alignItems: "center", gap: 10 },
  grupoCodigoInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    color: "#27242a",
    // El código se lee desde la pantalla de otra persona: monoespaciado y
    // espaciado para que no se confundan caracteres.
    fontFamily: "monospace",
    letterSpacing: 3,
  },
  grupoTarjeta: {
    borderWidth: 1,
    borderColor: "#efe9f0",
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  grupoCodigo: {
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,106,33,0.12)",
    gap: 2,
  },
  grupoCodigoTexto: {
    fontFamily: "monospace",
    letterSpacing: 4,
    fontSize: 20,
    fontWeight: "700",
    color: "#b4460f",
  },
  grupoParticipante: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  grupoTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#efe9f0",
    paddingTop: 8,
  },
  foodSearch: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 14,
    color: "#17131c",
    backgroundColor: "#fff",
  },
  foodChip: {
    minHeight: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2dee5",
    alignItems: "center",
    justifyContent: "center",
  },
  foodChipText: { color: flashDesign.color.inkSoft, fontSize: 12, fontWeight: "800" },
  foodChipActive: { backgroundColor: "#ff6a21", borderColor: "#ff6a21" },
  foodChipTextActive: { color: "#fff" },
  foodCard: {
    padding: 14,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e8e5eb",
    gap: 6,
  },
  foodMerchantCard: {
    overflow: "hidden",
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  foodMerchantBody: { gap: 10, paddingHorizontal: 14, paddingTop: 13, paddingBottom: 15 },
  foodMerchantTitleRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  foodMerchantName: {
    color: flashDesign.color.ink,
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  foodMerchantCuisine: { color: flashDesign.color.inkSoft, fontSize: 11, marginTop: 3 },
  foodRatingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "#FFF5DC",
  },
  foodRatingText: { color: "#7B5800", fontSize: 11, fontWeight: "900" },
  foodCardBanner: {
    height: 86,
    borderRadius: 16,
    backgroundColor: "#ffe1cc",
    justifyContent: "flex-start",
    padding: 10,
  },
  foodCardBannerLarge: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#ffe1cc",
    justifyContent: "flex-start",
    padding: 12,
  },
  foodMerchantBannerImage: {
    borderTopLeftRadius: flashDesign.radius.surface,
    borderTopRightRadius: flashDesign.radius.surface,
  },
  foodCardBannerImage: { borderRadius: 16 },
  foodCardTopline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  foodCardPromo: {
    color: "#fff",
    backgroundColor: flashDesign.color.food,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
  },
  foodCardBadge: {
    color: "#17131c",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "900",
  },
  shipmentHero: {
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#efe7ff",
  },
  shipmentHeroCopy: { marginTop: 7, color: "#655d70", lineHeight: 20 },
  shipmentBenefits: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  shipmentBenefit: {
    color: "#5d27aa",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
  },
};
