// Seguimiento y checkout: tracking sheet, checkout, propina y envíos.
// Estilos del cliente móvil — módulo ARC-001 (paso 10d).
import { flashDesign } from "../design-system";

export const customerTrackingStyleDefs = {
  trackingBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(20,15,24,.48)",
  },
  trackingSheet: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "92%",
    backgroundColor: "#fff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 18,
    gap: 15,
  },
  trackingHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  trackingMap: { height: 260, borderRadius: 20, overflow: "hidden", backgroundColor: "#e8e4ed" },
  nativeMapEmpty: {
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingHorizontal: 26,
    borderWidth: 1,
    borderColor: "#ded9e3",
  },
  nativeMapEmptyTitle: { color: "#17131c", fontSize: 14, fontWeight: "900", textAlign: "center" },
  nativeMapEmptyText: {
    color: "#716a76",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 16,
    textAlign: "center",
  },
  trackingMapCaption: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    backgroundColor: "rgba(255,255,255,.94)",
    borderRadius: 13,
    padding: 10,
  },
  trackingMapCaptionTitle: { fontSize: 13, fontWeight: "900", color: "#252128" },
  trackingMapCaptionText: { fontSize: 11, color: "#68616c", marginTop: 2 },
  trackingStatus: { gap: 4 },
  trackingProgress: { marginTop: 12, gap: 7 },
  trackingStage: { flexDirection: "row", alignItems: "center", gap: 9 },
  trackingStageDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#e3dfe6",
    alignItems: "center",
    justifyContent: "center",
  },
  trackingStageText: { fontSize: 12, color: "#918b95" },
  trackingStageTextActive: { fontWeight: "900", color: "#252128" },
  shipmentProtectionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#ded9e2",
    borderRadius: 15,
    padding: 11,
    backgroundColor: "#fff",
  },
  shipmentProtectionCardActive: { borderColor: "#73c894", backgroundColor: "#eefaf2" },
  shipmentProtectionIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#087a50",
    alignItems: "center",
    justifyContent: "center",
  },
  shipmentOptionRail: { gap: 9, paddingVertical: 2 },
  shipmentOptionCard: {
    minWidth: 92,
    minHeight: 70,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#ded9e2",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 12,
  },
  shipmentOptionCardActive: { backgroundColor: "#7c3cff", borderColor: "#7c3cff" },
  shipmentOptionText: { color: "#5c5362", fontSize: 12, fontWeight: "800" },
  shipmentOptionTextActive: { color: "#fff", fontSize: 12, fontWeight: "900" },
  shipmentOptionMeta: { color: "#918898", fontSize: 9, fontWeight: "700" },
  shipmentOptionMetaActive: { color: "#e5d9ff", fontSize: 9, fontWeight: "700" },
  errorText: { color: "#b42318", fontSize: 12, fontWeight: "700" },
  shipmentSlaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  shipmentSlaCard: {
    width: "48%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ded9e2",
    backgroundColor: "#fff",
    padding: 12,
  },
  shipmentSlaCardActive: { backgroundColor: "#17131c", borderColor: "#17131c" },
  shipmentSlaTitle: { color: "#231d27", fontWeight: "900" },
  shipmentSlaTitleActive: { color: "#fff", fontWeight: "900" },
  shipmentSlaCaption: { color: "#807785", fontSize: 11, marginTop: 2 },
  shipmentSlaCaptionActive: { color: "#d7cedc", fontSize: 11, marginTop: 2 },
  protectionQuoteText: { fontSize: 12, fontWeight: "800", color: "#087a50", marginTop: 5 },
  returnStatusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#f2edff",
    borderRadius: 12,
    padding: 11,
    marginTop: 10,
  },
  allergenWarning: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
    backgroundColor: "#fff4df",
    borderWidth: 1,
    borderColor: "#ffd69a",
    borderRadius: 14,
    padding: 12,
  },
  allergenWarningTitle: { fontSize: 13, fontWeight: "900", color: "#7c3b00" },
  allergenWarningText: { fontSize: 11, lineHeight: 16, color: "#7c4c20" },
  modifierCounter: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: flashDesign.color.warningSoft,
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  modifierRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    borderTopWidth: 1,
    borderTopColor: flashDesign.color.line,
  },
  modifierRowSelected: { backgroundColor: "#FFF9F5" },
  modifierRowBlocked: { opacity: 0.42 },
  modifierControl: {
    width: 23,
    height: 23,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#C8C1CC",
    backgroundColor: flashDesign.color.surface,
  },
  modifierControlSelected: {
    backgroundColor: flashDesign.color.food,
    borderColor: flashDesign.color.food,
  },
  modifierName: { flex: 1, color: flashDesign.color.ink, fontSize: 12, fontWeight: "800" },
  modifierPrice: { color: flashDesign.color.inkSoft, fontSize: 10, fontWeight: "800" },
  foodCustomizerNoteSection: {
    gap: 10,
    padding: 13,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCustomizerNoteHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  foodCustomizerNoteCount: { color: flashDesign.color.muted, fontSize: 9, fontWeight: "800" },
  productNote: {
    minHeight: 92,
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    backgroundColor: flashDesign.color.canvas,
    color: flashDesign.color.ink,
    fontSize: 12,
    textAlignVertical: "top",
  },
  productCustomizerAction: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 18,
    backgroundColor: flashDesign.color.food,
    shadowColor: flashDesign.color.food,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 3,
  },
  productCustomizerActionCount: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.18)",
  },
  productCustomizerActionCountText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  productCustomizerActionText: { flex: 1, color: "#fff", fontSize: 13, fontWeight: "900" },
  productCustomizerActionPrice: { color: "#fff", fontSize: 13, fontWeight: "900" },
  foodCheckoutHero: {
    minHeight: 190,
    gap: 8,
    padding: 18,
    borderRadius: flashDesign.radius.surface,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.14,
    shadowRadius: 22,
    elevation: 4,
  },
  foodCheckoutHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  foodCheckoutVerified: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "rgba(8,122,80,.25)",
  },
  foodCheckoutVerifiedText: {
    color: "#BDF3D7",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  foodCheckoutExpiry: { color: "rgba(255,255,255,.6)", fontSize: 9, fontWeight: "800" },
  foodCheckoutMerchant: {
    color: "#fff",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "900",
    letterSpacing: -0.5,
    marginTop: 7,
  },
  foodCheckoutEta: { color: "rgba(255,255,255,.72)", fontSize: 12 },
  foodCheckoutHeroFacts: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    marginTop: "auto",
    paddingTop: 13,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,.12)",
  },
  foodCheckoutHeroDivider: { width: 1, height: 30, backgroundColor: "rgba(255,255,255,.16)" },
  foodCheckoutHeroFactLabel: {
    color: "rgba(255,255,255,.52)",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  foodCheckoutHeroFactValue: { color: "#fff", fontSize: 11, fontWeight: "900", marginTop: 3 },
  foodCheckoutInfoList: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCheckoutInfoCard: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
  },
  foodCheckoutInfoIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  foodCheckoutInfoTitle: {
    color: flashDesign.color.muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  foodCheckoutInfoValue: {
    color: flashDesign.color.ink,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "900",
    marginTop: 2,
  },
  foodCheckoutInfoMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCheckoutItems: {
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  checkoutItem: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: flashDesign.color.line,
  },
  foodCheckoutItemQuantity: {
    minWidth: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCheckoutItemQuantityText: {
    color: flashDesign.color.foodDeep,
    fontSize: 11,
    fontWeight: "900",
  },
  foodCheckoutItemName: { color: flashDesign.color.ink, fontSize: 12, fontWeight: "900" },
  foodCheckoutItemMeta: { color: flashDesign.color.inkSoft, fontSize: 9, marginTop: 3 },
  foodCheckoutItemNote: {
    color: flashDesign.color.inkSoft,
    fontSize: 9,
    lineHeight: 13,
    fontStyle: "italic",
    marginTop: 3,
  },
  foodCheckoutItemPrice: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodCheckoutTotals: {
    gap: 2,
    padding: 15,
    borderRadius: 20,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
  },
  foodCheckoutTotalLabel: { color: flashDesign.color.inkSoft, fontSize: 11, fontWeight: "700" },
  foodCheckoutTotalAmount: { color: flashDesign.color.ink, fontSize: 11, fontWeight: "900" },
  foodCheckoutDiscountLabel: { color: flashDesign.color.shipment, fontSize: 11, fontWeight: "800" },
  foodCheckoutDiscountAmount: {
    color: flashDesign.color.shipment,
    fontSize: 11,
    fontWeight: "900",
  },
  foodCheckoutTotalDivider: {
    height: 1,
    backgroundColor: flashDesign.color.line,
    marginVertical: 4,
  },
  foodCheckoutGrandLabel: { color: flashDesign.color.ink, fontSize: 17, fontWeight: "900" },
  foodCheckoutGrandAmount: { color: flashDesign.color.ink, fontSize: 20, fontWeight: "900" },
  foodCheckoutSecurity: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 17,
    backgroundColor: flashDesign.color.successSoft,
  },
  foodCheckoutSecurityIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: flashDesign.color.surface,
  },
  foodCheckoutSecurityText: {
    flex: 1,
    color: flashDesign.color.shipment,
    fontSize: 10,
    lineHeight: 15,
    fontWeight: "700",
  },
  foodCheckoutRefresh: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#FFD0B8",
    backgroundColor: flashDesign.color.warningSoft,
  },
  foodCheckoutRefreshText: { color: flashDesign.color.foodDeep, fontSize: 12, fontWeight: "900" },
  proofCameraButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 13,
    backgroundColor: "#18151d",
  },
  complianceHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  complianceBadge: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.7,
    color: "#7c3cff",
    backgroundColor: "#efe7ff",
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 10,
  },
  complianceBadgeApproved: { color: "#087a50", backgroundColor: "#e5f8f0" },
  complianceBadgeRejected: { color: "#b3302c", backgroundColor: "#ffe9e7" },
  complianceDocuments: { gap: 8 },
  complianceDocumentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 11,
    borderRadius: 15,
    backgroundColor: "#faf8fb",
  },
  complianceRejection: { fontSize: 11, color: "#b3302c", fontWeight: "700" },
  newAddressFields: { flexDirection: "row", gap: 8 },
  addressLabelInput: { width: 92 },
  addressTextInput: { flex: 1 },
  primaryButton: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 15,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
  },
  primaryButtonText: { color: "#fff", fontWeight: "900" },
  disabledButton: { opacity: 0.45 },

  // Propina en el checkout (GTM-001). Los objetivos táctiles son de 44px: es la
  // única decisión del checkout que se toma con el pulgar sobre una lista de
  // montos parecidos, y ahí un objetivo chico hace dejar la propina equivocada.
  propinaSelector: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#efe9f0",
    padding: 16,
    gap: 8,
  },
  propinaOpciones: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  propinaOpcion: {
    minHeight: 44,
    minWidth: 78,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    alignItems: "center",
    justifyContent: "center",
  },
  // Se marca con borde y fondo, no sólo con color: un cambio de color solo no lo
  // distingue quien no separa esos dos tonos.
  propinaOpcionActiva: { borderColor: "#ff6a21", backgroundColor: "rgba(255,106,33,0.10)" },
  propinaOpcionTexto: { color: "#27242a", fontWeight: "700" },
  propinaOpcionMonto: { color: "#6c6870", fontSize: 12 },
  propinaLibre: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  propinaInput: {
    minHeight: 44,
    width: 120,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    textAlign: "right",
    color: "#27242a",
  },

  // Suscripción de Flash (GTM-001). Espeja `accountCard` para que la pantalla de
  // cuenta no cambie de idioma visual a mitad de scroll.
  suscripcionCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#efe9f0",
    padding: 18,
    gap: 10,
  },
  suscripcionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  suscripcionPrecio: { fontSize: 20, fontWeight: "700", color: "#27242a" },
  suscripcionChip: {
    backgroundColor: "rgba(22,163,74,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  // Cancelada pero vigente: ámbar y no rojo, porque los beneficios siguen y un
  // rojo diría que ya se perdieron.
  suscripcionChipVence: {
    backgroundColor: "rgba(217,119,6,0.12)",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  suscripcionChipText: { fontSize: 12, color: "#27242a" },
  suscripcionAviso: { fontSize: 13, color: "#b45309" },
  suscripcionAlta: {
    backgroundColor: "#ff6a21",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  suscripcionAltaText: { color: "#ffffff", fontWeight: "700" },
  // La baja es secundaria, no destructiva: no se esconde ni se pinta de peligro.
  suscripcionBaja: {
    borderWidth: 1,
    borderColor: "#efe9f0",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  suscripcionBajaText: { color: "#27242a", fontWeight: "600" },
  suscripcionOk: { fontSize: 13, color: "#087a50" },
  suscripcionError: { fontSize: 13, color: "#b91c1c" },

  // Pedidos grupales (GTM-001). Reutiliza la tarjeta de suscripción para que la
  // pantalla no cambie de idioma visual a mitad de scroll.
  grupoSumarse: { flexDirection: "row", alignItems: "center", gap: 10 },
  grupoCodigoInput: {
    flex: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#efe9f0",
    color: "#27242a",
    // El código se lee desde la pantalla de otra persona: monoespaciado y
    // espaciado para que no se confundan caracteres.
    fontFamily: "monospace",
    letterSpacing: 3,
  },
  grupoTarjeta: {
    borderWidth: 1,
    borderColor: "#efe9f0",
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  grupoCodigo: {
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255,106,33,0.12)",
    gap: 2,
  },
  grupoCodigoTexto: {
    fontFamily: "monospace",
    letterSpacing: 4,
    fontSize: 20,
    fontWeight: "700",
    color: "#b4460f",
  },
  grupoParticipante: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  grupoTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#efe9f0",
    paddingTop: 8,
  },
  foodSearch: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 14,
    color: "#17131c",
    backgroundColor: "#fff",
  },
  foodChip: {
    minHeight: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2dee5",
    alignItems: "center",
    justifyContent: "center",
  },
  foodChipText: { color: flashDesign.color.inkSoft, fontSize: 12, fontWeight: "800" },
  foodChipActive: { backgroundColor: "#ff6a21", borderColor: "#ff6a21" },
  foodChipTextActive: { color: "#fff" },
  foodCard: {
    padding: 14,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e8e5eb",
    gap: 6,
  },
  foodMerchantCard: {
    overflow: "hidden",
    borderRadius: flashDesign.radius.surface,
    backgroundColor: flashDesign.color.surface,
    borderWidth: 1,
    borderColor: flashDesign.color.line,
    shadowColor: flashDesign.color.ink,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  foodMerchantBody: { gap: 10, paddingHorizontal: 14, paddingTop: 13, paddingBottom: 15 },
  foodMerchantTitleRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  foodMerchantName: {
    color: flashDesign.color.ink,
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: -0.2,
  },
  foodMerchantCuisine: { color: flashDesign.color.inkSoft, fontSize: 11, marginTop: 3 },
  foodRatingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: flashDesign.radius.pill,
    backgroundColor: "#FFF5DC",
  },
  foodRatingText: { color: "#7B5800", fontSize: 11, fontWeight: "900" },
  foodCardBanner: {
    height: 86,
    borderRadius: 16,
    backgroundColor: "#ffe1cc",
    justifyContent: "flex-start",
    padding: 10,
  },
  foodCardBannerLarge: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#ffe1cc",
    justifyContent: "flex-start",
    padding: 12,
  },
  foodMerchantBannerImage: {
    borderTopLeftRadius: flashDesign.radius.surface,
    borderTopRightRadius: flashDesign.radius.surface,
  },
  foodCardBannerImage: { borderRadius: 16 },
  foodCardTopline: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  foodCardPromo: {
    color: "#fff",
    backgroundColor: flashDesign.color.food,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
  },
  foodCardBadge: {
    color: "#17131c",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "900",
  },
  shipmentHero: {
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#efe7ff",
  },
  shipmentHeroCopy: { marginTop: 7, color: "#655d70", lineHeight: 20 },
  shipmentBenefits: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  shipmentBenefit: {
    color: "#5d27aa",
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
  },
};
