// Estilos del repartidor móvil (ARC-001, paso 10c).
// Extraídos de `styles.ts` para builds por variante sin arrastrar la hoja entera.

export const driverStyleDefs = {
  hero: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#f4511e",
  },
  cardDark: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: "#161b22",
  },
  heroLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  heroTitle: {
    marginTop: 6,
    color: "#fff",
    fontSize: 21,
    fontWeight: "900",
  },
  heroCopy: {
    marginTop: 6,
    color: "rgba(255,255,255,0.76)",
    lineHeight: 20,
  },
  gpsText: {
    marginTop: 8,
    color: "#8df0c3",
    fontSize: 12,
    fontWeight: "900",
  },
  kpiGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 10,
  },
  kpi: {
    width: "47.8%",
    minHeight: 84,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e6e9ef",
  },
  kpiLabel: {
    color: "#626a78",
    fontSize: 12,
    fontWeight: "900",
  },
  kpiValue: {
    marginTop: 10,
    color: "#222832",
    fontSize: 22,
    fontWeight: "900",
  },
  sectionTitle: {
    color: "#222832",
    fontSize: 17,
    fontWeight: "900",
  },
  card: {
    padding: 14,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e6e9ef",
    gap: 5,
  },
  cardTitle: {
    color: "#222832",
    fontSize: 16,
    fontWeight: "900",
  },
  cardText: {
    color: "#626a78",
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eef0f3",
  },
  itemCopy: {
    flex: 1,
    gap: 3,
  },
  itemName: {
    color: "#222832",
    fontWeight: "800",
  },
  formCard: {
    padding: 14,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e6e9ef",
    gap: 10,
  },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: "#d8dde5",
    borderRadius: 8,
    paddingHorizontal: 12,
    color: "#222832",
    backgroundColor: "#fff",
  },
  secondaryAction: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#f4511e",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryActionText: {
    color: "#d74317",
    fontWeight: "800",
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choice: {
    minWidth: 70,
    minHeight: 36,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: "#eef0f3",
    alignItems: "center",
    justifyContent: "center",
  },
  choiceActive: {
    backgroundColor: "#f4511e",
  },
  choiceText: {
    color: "#626a78",
    fontWeight: "800",
    textTransform: "capitalize",
  },
  choiceTextActive: {
    color: "#fff",
  },
  helperText: {
    color: "#627080",
    fontSize: 12,
  },
  quoteBox: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#e8f7ef",
    gap: 4,
  },
  rideHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  rideEyebrow: {
    color: "#7c3cff",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.4,
  },
  rideTitle: {
    color: "#15131a",
    fontSize: 28,
    fontWeight: "900",
    marginTop: 3,
  },
  livePill: {
    backgroundColor: "#eaf9f1",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  livePillText: {
    color: "#087a4b",
    fontSize: 12,
    fontWeight: "900",
  },
  navigationCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 13,
    borderRadius: 19,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5dfeb",
    shadowColor: "#32115d",
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  navigationTurn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  navigationLabel: {
    color: "#7c3cff",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  navigationInstruction: {
    color: "#17131c",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 3,
  },
  navigationNext: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: "#f0e7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  driverShell: {
    flex: 1,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    backgroundColor: "#f7f6f9",
  },
  driverContent: { padding: 14, paddingBottom: 26, gap: 12 },
  driverAppHeader: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 2,
  },
  driverBrand: { color: "#7c3cff", fontSize: 10, fontWeight: "900", letterSpacing: 1.5 },
  driverGreeting: { color: "#17131c", fontSize: 25, fontWeight: "900", marginTop: 2 },
  driverHeaderAction: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ebe5ef",
  },
  driverBottomNav: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    paddingTop: 7,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e6e0e9",
    shadowColor: "#241331",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -4 },
    elevation: 16,
  },
  driverBottomItem: {
    flex: 1,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  driverBottomIconWrap: { position: "relative", minWidth: 25, alignItems: "center" },
  driverBottomDot: {
    position: "absolute",
    right: -2,
    top: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ef3b57",
    borderWidth: 1.5,
    borderColor: "#fff",
  },
  driverBottomLabel: { color: "#8a828f", fontSize: 10, fontWeight: "800" },
  driverBottomLabelActive: { color: "#7c3cff" },
  driverEarningsHero: {
    minHeight: 185,
    borderRadius: 28,
    padding: 22,
    justifyContent: "center",
    shadowColor: "#35115f",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  driverEarningsLabel: {
    color: "rgba(255,255,255,.68)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.3,
  },
  driverEarningsValue: { color: "#fff", fontSize: 38, fontWeight: "900", marginTop: 9 },
  driverEarningsCopy: {
    color: "rgba(255,255,255,.78)",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 10,
    maxWidth: 360,
  },
  driverEarningsError: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#fff0ef",
    borderWidth: 1,
    borderColor: "#f1cfcc",
  },
  driverPeriodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  driverPeriodCard: {
    flex: 1,
    minWidth: 150,
    minHeight: 112,
    borderRadius: 21,
    padding: 15,
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e3ed",
  },
  driverPeriodLabel: { color: "#7c3cff", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  driverPeriodValue: { color: "#17131c", fontSize: 21, fontWeight: "900", marginTop: 8 },
  driverPeriodMeta: { color: "#77707b", fontSize: 10, fontWeight: "700", marginTop: 5 },
  driverWeekChartCard: {
    borderRadius: 25,
    padding: 18,
    gap: 13,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e3ed",
  },
  driverWeekChartTotal: {
    color: "#17131c",
    fontSize: 16,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  driverWeekChart: { minHeight: 146, flexDirection: "row", alignItems: "flex-end", gap: 5 },
  driverWeekColumn: { flex: 1, minWidth: 0, alignItems: "center" },
  driverWeekColumnSelected: { backgroundColor: "#f2eaff", borderRadius: 10 },
  driverWeekAmount: {
    color: "#5f5764",
    fontSize: 8,
    fontWeight: "800",
    marginBottom: 4,
    fontVariant: ["tabular-nums"],
  },
  driverWeekAmountNegative: { color: "#a33939" },
  driverWeekUpper: { width: "100%", height: 54, alignItems: "center", justifyContent: "flex-end" },
  driverWeekLower: {
    width: "100%",
    height: 54,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  driverWeekBar: {
    width: "58%",
    maxWidth: 24,
    minWidth: 7,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
  },
  driverWeekBaseline: { width: "100%", height: 1, backgroundColor: "#d8d1dc" },
  driverWeekDay: { color: "#817985", fontSize: 8, fontWeight: "900", marginTop: 5 },
  driverWeekDaySelected: { color: "#7c3cff" },
  driverWeekDetail: { gap: 11, padding: 13, borderRadius: 18, backgroundColor: "#f8f6fa" },
  driverWeekDetailHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  driverWeekDetailDate: { color: "#17131c", fontSize: 14, fontWeight: "900", marginTop: 3 },
  driverWeekDetailAmount: {
    color: "#17131c",
    fontSize: 16,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  driverWeekDetailGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  driverWeekDetailMetric: {
    width: "48%",
    minHeight: 54,
    padding: 9,
    borderRadius: 13,
    backgroundColor: "#fff",
  },
  driverWeekDetailValue: {
    color: "#28222c",
    fontSize: 13,
    fontWeight: "900",
    marginTop: 5,
    fontVariant: ["tabular-nums"],
  },
  driverTimeCard: {
    borderRadius: 25,
    padding: 18,
    gap: 15,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e3ed",
    shadowColor: "#2b1738",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  driverTimeTitle: { color: "#17131c", fontSize: 22, fontWeight: "900", marginTop: 3 },
  driverTimeClock: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0e7ff",
  },
  driverTimeGrid: { flexDirection: "row", gap: 10 },
  driverTimeMetric: {
    flex: 1,
    minWidth: 0,
    minHeight: 105,
    padding: 14,
    borderRadius: 19,
    backgroundColor: "#f8f6fa",
  },
  driverTimeMetricTop: { flexDirection: "row", alignItems: "center", gap: 7 },
  driverTimeDot: { width: 8, height: 8, borderRadius: 4 },
  driverTimeLabel: { color: "#6f6874", fontSize: 9, fontWeight: "900", letterSpacing: 0.8 },
  driverTimeValue: {
    color: "#17131c",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 12,
    fontVariant: ["tabular-nums"],
  },
  driverTimeMeta: { color: "#77707b", fontSize: 10, fontWeight: "600", marginTop: 5 },
  driverTimeRatio: { gap: 7 },
  driverTimeTrack: { height: 7, borderRadius: 4, overflow: "hidden", backgroundColor: "#e9e3ed" },
  driverTimeFill: { height: "100%", minWidth: 3, borderRadius: 4, backgroundColor: "#087a50" },
  driverTimeRatioText: { color: "#5e5663", fontSize: 10, fontWeight: "700" },
  driverTimeWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 11,
    borderRadius: 14,
    backgroundColor: "#fff6e8",
  },
  driverTimeWarningText: {
    flex: 1,
    color: "#80500b",
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "600",
  },
  driverTimeWeek: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingTop: 2,
  },
  driverTimeWeekLabel: { color: "#7c3cff", fontSize: 9, fontWeight: "900", letterSpacing: 1 },
  driverTimeWeekValue: { color: "#3e3742", fontSize: 11, fontWeight: "800" },
  driverTimeWeekDivider: { width: 3, height: 3, borderRadius: 2, backgroundColor: "#aaa1af" },
  driverTimeSource: { color: "#89818d", fontSize: 9, lineHeight: 14, fontWeight: "600" },
  driverTimeUnavailable: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    padding: 15,
    borderRadius: 20,
    backgroundColor: "#fff0ef",
    borderWidth: 1,
    borderColor: "#f1cfcc",
  },
  driverEarningRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee9f1",
  },
  driverEarningAdjustment: { backgroundColor: "#fff0ef" },
  driverEarningAmount: {
    color: "#087a50",
    fontSize: 14,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  driverEarningAmountNegative: { color: "#a33939" },
  driverPreferenceOptions: { gap: 9, marginTop: 4 },
  driverPreferenceOption: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 12,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#e8e1ec",
    backgroundColor: "#faf9fb",
  },
  driverPreferenceOptionActive: { borderColor: "#7c3cff", backgroundColor: "#f5efff" },
  driverPreferenceRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#a39aa8",
    alignItems: "center",
    justifyContent: "center",
  },
  driverPreferenceRadioActive: { borderColor: "#7c3cff" },
  driverPreferenceDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#7c3cff" },
  driverDemandLoading: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 18,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e3ed",
  },
  driverDemandError: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#fff5f2",
    borderWidth: 1,
    borderColor: "#f0d6d0",
  },
  driverDemandRail: { gap: 10, paddingVertical: 2, paddingRight: 14 },
  driverDemandCard: {
    width: 194,
    minHeight: 132,
    gap: 5,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e8e1ec",
  },
  driverDemandCardCurrent: { borderColor: "#7c3cff", borderWidth: 2, backgroundColor: "#faf7ff" },
  driverDemandCardTop: { minHeight: 19, flexDirection: "row", alignItems: "center", gap: 6 },
  driverDemandLevelDot: { width: 8, height: 8, borderRadius: 4 },
  driverDemandLevel: { fontSize: 9, fontWeight: "900", letterSpacing: 1 },
  driverDemandHere: {
    marginLeft: "auto",
    color: "#7c3cff",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  driverDemandName: { color: "#17131c", fontSize: 20, fontWeight: "900", marginTop: 2 },
  driverDemandJobs: { color: "#37303b", fontSize: 12, fontWeight: "800", marginTop: 3 },
  driverDemandSupply: { color: "#77707b", fontSize: 10, fontWeight: "700" },
  driverInsightCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 21,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e9e3ed",
  },
  driverInsightIcon: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#f0e7ff",
    alignItems: "center",
    justifyContent: "center",
  },
  driverTransparencyCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    borderRadius: 21,
    backgroundColor: "#eaf8f0",
    borderWidth: 1,
    borderColor: "#cdebd9",
  },
  driverSectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  driverSectionEyebrow: { color: "#7c3cff", fontSize: 10, fontWeight: "900", letterSpacing: 1.3 },
  driverSectionTitle: { color: "#17131c", fontSize: 28, fontWeight: "900", marginTop: 3 },
  driverUnreadBadge: {
    minWidth: 36,
    height: 36,
    paddingHorizontal: 10,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#7c3cff",
  },
  driverUnreadText: { color: "#fff", fontWeight: "900", fontVariant: ["tabular-nums"] },
  driverInboxRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#eee9f1",
  },
  driverInboxUnread: {
    backgroundColor: "#f7f1ff",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 14,
  },
  driverInboxIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#f0e8ff",
    alignItems: "center",
    justifyContent: "center",
  },
  driverEmptyState: {
    minHeight: 160,
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    padding: 20,
  },
  driverNavScreen: { flex: 1, backgroundColor: "#15121a" },
  driverNavTop: {
    minHeight: 108,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#15121a",
  },
  driverNavClose: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,.12)",
  },
  driverNavTurn: {
    width: 58,
    height: 58,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#caff3d",
  },
  driverNavPhase: { color: "#caff3d", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 },
  driverNavInstruction: {
    color: "#fff",
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
    marginTop: 4,
  },
  driverNavDistance: {
    color: "rgba(255,255,255,.7)",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 3,
  },
  driverNavSheet: {
    flex: 1,
    backgroundColor: "#fff",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    marginTop: -22,
  },
  driverNavSheetContent: { padding: 18, paddingTop: 22, paddingBottom: 34, gap: 12 },
  driverNavEtaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  driverNavEta: { color: "#17131c", fontSize: 31, fontWeight: "900" },
  driverNavKind: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  driverNavDestinationLabel: {
    color: "#7c3cff",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 1.2,
    marginTop: 3,
  },
  driverNavDestination: { color: "#17131c", fontSize: 17, lineHeight: 22, fontWeight: "900" },
  driverNavStep: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    minHeight: 54,
    paddingVertical: 7,
    borderTopWidth: 1,
    borderTopColor: "#eee9f1",
  },
  driverNavStepIndex: {
    width: 31,
    height: 31,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#6f6874",
  },
  driverNavStepIndexText: { color: "#fff", fontWeight: "900" },
  driverNavStepText: { color: "#241f29", fontSize: 14, fontWeight: "800" },
  driverNavActions: { flexDirection: "row", gap: 10, marginTop: 4 },
  driverNavSecondary: {
    minHeight: 52,
    paddingHorizontal: 18,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#f0edf2",
  },
  driverNavSecondaryText: { color: "#17131c", fontWeight: "900" },
  driverNavPrimary: {
    flex: 1,
    minHeight: 52,
    paddingHorizontal: 14,
    borderRadius: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#17131c",
  },
  driverNavDisclaimer: {
    color: "#766e7b",
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 2,
  },
  driverNavigation: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#f4edff",
    borderWidth: 2,
    borderColor: "#7c3cff",
  },
  dispatchOffer: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: "#ebe7f3",
    shadowColor: "#251445",
    shadowOpacity: 0.09,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  dispatchOfferHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  dispatchOfferIcon: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  dispatchOfferType: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.1,
    color: "#7c3cff",
  },
  dispatchOfferTimer: {
    fontSize: 20,
    fontWeight: "900",
    color: "#17131d",
    fontVariant: ["tabular-nums"],
  },
  dispatchOfferFare: { fontSize: 19, fontWeight: "900", color: "#17131d" },
  dispatchRoute: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingLeft: 5,
  },
  routeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#27ae60",
    borderWidth: 2,
    borderColor: "#d8f7e5",
  },
  routeDotDestination: { backgroundColor: "#7c3cff", borderColor: "#e7dcff" },
  dispatchAddress: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: "#312b39",
  },
  offerActions: { flexDirection: "row", gap: 10, marginTop: 2 },
  rejectOfferButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ded7e8",
    alignItems: "center",
    justifyContent: "center",
  },
  rejectOfferText: { fontWeight: "800", color: "#5f5669" },
  acceptOfferButton: {
    flex: 2,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: "#17131d",
    alignItems: "center",
    justifyContent: "center",
  },
  acceptOfferText: { fontWeight: "900", color: "#fff" },
  quickPlacesRail: { gap: 9, paddingBottom: 2 },
  quickPlace: {
    width: 180,
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 9,
    borderRadius: 17,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e7e3eb",
  },
  quickPlaceIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    backgroundColor: "#f0e8ff",
    alignItems: "center",
    justifyContent: "center",
  },
  quickPlaceCopy: { flex: 1, minWidth: 0 },
  quickPlaceEmpty: {
    width: 220,
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 12,
    borderRadius: 17,
    backgroundColor: "#f7f2ff",
    borderWidth: 1,
    borderColor: "#e3d8f4",
  },
  quickPlaceTitle: { color: "#17131c", fontSize: 12, fontWeight: "900" },
  quickPlaceAddress: {
    color: "#77717c",
    fontSize: 10,
    marginTop: 2,
    maxWidth: 112,
  },
  rideSheet: {
    padding: 14,
    marginTop: -28,
    marginHorizontal: 8,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e7e3eb",
    gap: 10,
  },
  rideOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
    backgroundColor: "#f7f5f9",
  },
  rideOptionActive: { borderColor: "#7c3cff", backgroundColor: "#f3ecff" },
  vehicleBadge: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#17131c",
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleIcon: { color: "#fff", fontSize: 14, fontWeight: "900" },
  rideOptionCopy: { flex: 1 },
  rideOptionTitle: { color: "#17131c", fontSize: 15, fontWeight: "900" },
  ridePrice: { color: "#17131c", fontSize: 15, fontWeight: "900" },
  routeSummary: {
    color: "#5f5868",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
  },
  fareBreakdown: {
    padding: 13,
    borderRadius: 17,
    backgroundColor: "#f8f6fa",
    borderWidth: 1,
    borderColor: "#e9e4ed",
    gap: 7,
  },
  fareBreakdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  fareTotal: { color: "#17131c", fontSize: 20, fontWeight: "900" },
  fareLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  demandText: { color: "#7c3cff", fontSize: 12, fontWeight: "900" },
  safetyStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 13,
    borderRadius: 18,
    backgroundColor: "#eefaf4",
    borderWidth: 1,
    borderColor: "#d4f0e2",
  },
  safetyIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  safetyTitle: { color: "#164c36", fontWeight: "900", marginBottom: 2 },
  totalText: {
    color: "#222832",
    fontWeight: "900",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
  },
  action: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: "#252b33",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  actionDisabled: {
    opacity: 0.55,
  },
  actionText: {
    color: "#fff",
    fontWeight: "900",
    textAlign: "center",
    flexShrink: 1,
  },
  signatureBackdrop: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "rgba(20,16,24,.48)",
    justifyContent: "flex-end",
  },
  signatureSheet: {
    width: "100%",
    maxWidth: 620,
    backgroundColor: "#fff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 20,
    paddingBottom: 32,
    gap: 14,
  },
  signatureRelationshipRow: { flexDirection: "row", gap: 8 },
  signatureChoice: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#ded9e2",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  signatureChoiceActive: { backgroundColor: "#17131c", borderColor: "#17131c" },
  signatureChoiceText: { fontWeight: "800", fontSize: 12, color: "#5f5864", textAlign: "center" },
  signatureChoiceTextActive: {
    fontWeight: "800",
    fontSize: 12,
    color: "#fff",
    textAlign: "center",
  },
  signatureCanvas: {
    height: 210,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#cbc4d0",
    borderStyle: "dashed",
    backgroundColor: "#fff",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  signatureGuide: { color: "#aaa1ae", fontWeight: "700", fontSize: 16 },
  signatureActions: { flexDirection: "row", gap: 10 },
  shipmentTrackingSummary: {
    marginTop: 12,
    padding: 15,
    borderRadius: 18,
    backgroundColor: "#f6f2f8",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  shipmentTrackingBadge: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
    alignItems: "center",
    justifyContent: "center",
  },
  shipmentPinCard: {
    marginTop: 12,
    borderRadius: 18,
    backgroundColor: "#17131c",
    padding: 16,
    alignItems: "center",
  },
  shipmentPin: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 8,
    marginVertical: 4,
  },
  referralCode: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: 3,
    marginVertical: 6,
    textAlign: "center",
  },
  secondaryButton: {
    minHeight: 50,
    paddingHorizontal: 22,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#d7d0dc",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  secondaryButtonText: { color: "#342e38", fontWeight: "900" },
};
