// Estilos de la consola comercio móvil (ARC-001, paso 10b).
//
// Extraídos de `styles.ts` para habilitar builds por variante sin arrastrar
// la hoja entera. Se fusionan en el compositor vía spread antes de
// `StyleSheet.create`.
import { Platform } from "react-native";

export const merchantStyleDefs = {
  merchantHero: {
    padding: 20,
    borderRadius: 24,
    minHeight: 174,
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  merchantShell: { flex: 1, backgroundColor: "#f6f3f0" },
  merchantContent: {
    padding: 14,
    paddingBottom: 30,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  merchantScreenHeading: { paddingTop: 5, paddingBottom: 5, gap: 4 },
  merchantScreenEyebrow: { color: "#ef641f", fontSize: 10, fontWeight: "900", letterSpacing: 1.3 },
  merchantScreenTitle: { color: "#201b18", fontSize: 27, fontWeight: "900", letterSpacing: -0.7 },
  merchantScreenCopy: { color: "#736962", fontSize: 13, lineHeight: 19 },
  merchantOrderSummary: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  merchantOrderSummaryItem: {
    minWidth: "22%",
    flexGrow: 1,
    padding: 11,
    borderRadius: 15,
    backgroundColor: "#241a14",
  },
  merchantOrderSummaryValue: { color: "#fff", fontSize: 21, fontWeight: "900" },
  merchantOrderSummaryLabel: {
    marginTop: 3,
    color: "rgba(255,255,255,.62)",
    fontSize: 10,
    fontWeight: "800",
  },
  merchantEmpty: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 20,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e7e1dc",
  },
  merchantEmptyTitle: { color: "#211c18", fontSize: 18, fontWeight: "900" },
  merchantEmptyCopy: { color: "#756c65", fontSize: 12, textAlign: "center" },
  merchantOrderActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  merchantOrderDetailAction: {
    flex: 1,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
    backgroundColor: "#fff0e7",
    borderWidth: 1,
    borderColor: "#ffd4bc",
  },
  merchantOrderDetailActionText: { color: "#9a3e12", fontSize: 12, fontWeight: "900" },
  merchantDetailBackdrop: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    backgroundColor: "rgba(24,16,12,.58)",
  },
  merchantDetailSheet: {
    width: "100%",
    maxWidth: 620,
    height: "94%",
    maxHeight: 900,
    paddingHorizontal: 18,
    paddingTop: 9,
    paddingBottom: Math.max(18, Platform.OS === "ios" ? 26 : 18),
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#f8f5f2",
  },
  merchantDetailHeading: { flex: 1, gap: 2 },
  merchantDetailTitle: { color: "#211b17", fontSize: 24, fontWeight: "900", letterSpacing: -0.5 },
  merchantDetailSubtitle: { color: "#766d66", fontSize: 11, fontWeight: "700" },
  merchantDetailScroll: { flex: 1 },
  merchantDetailContent: { gap: 13, paddingTop: 14, paddingBottom: 18 },
  merchantDetailFacts: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  merchantDetailFact: {
    flex: 1,
    minWidth: 120,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#fff",
  },
  merchantDetailFactLabel: {
    color: "#8a7f77",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  merchantDetailFactValue: { marginTop: 4, color: "#211b17", fontSize: 14, fontWeight: "900" },
  merchantDetailSection: {
    gap: 9,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe4df",
  },
  merchantDetailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  merchantDetailSectionTitle: { color: "#211b17", fontSize: 18, fontWeight: "900" },
  merchantDetailItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#eee8e3",
  },
  merchantDetailItemSelected: {
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 14,
    backgroundColor: "#fff5ef",
    borderTopColor: "transparent",
  },
  merchantDetailQuantity: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 11,
    backgroundColor: "#211813",
  },
  merchantDetailQuantityText: { color: "#fff", fontSize: 12, fontWeight: "900" },
  merchantDetailItemCopy: { flex: 1, gap: 4 },
  merchantDetailItemTitleRow: { flexDirection: "row", alignItems: "center", gap: 7 },
  merchantDetailItemTitle: { flex: 1, color: "#251f1b", fontSize: 14, fontWeight: "900" },
  merchantDetailItemPrice: { color: "#ef641f", fontSize: 11, fontWeight: "900" },
  merchantDetailItemMeta: { color: "#766d66", fontSize: 11, lineHeight: 16 },
  merchantUnavailableBadge: {
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
    color: "#a33b28",
    backgroundColor: "#ffe8e2",
    fontSize: 8,
    fontWeight: "900",
  },
  merchantKitchenNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    padding: 9,
    borderRadius: 11,
    backgroundColor: "#fff1e8",
  },
  merchantKitchenNoteText: {
    flex: 1,
    color: "#7c3c1c",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 16,
  },
  merchantSubstitutionTrigger: {
    alignSelf: "flex-start",
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    borderRadius: 12,
    backgroundColor: "#fff0e7",
    borderWidth: 1,
    borderColor: "#ffd4bc",
  },
  merchantSubstitutionTriggerText: { color: "#9a3e12", fontSize: 11, fontWeight: "900" },
  merchantSubstitutionComposer: {
    gap: 11,
    padding: 15,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#ffcfb4",
  },
  merchantReplacementList: { gap: 7 },
  merchantReplacementOption: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 10,
    borderRadius: 15,
    backgroundColor: "#faf7f5",
    borderWidth: 1,
    borderColor: "#e8e1dc",
  },
  merchantReplacementOptionActive: { backgroundColor: "#fff0e7", borderColor: "#ef641f" },
  merchantReplacementRadio: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 2,
    borderColor: "#ef641f",
  },
  merchantReplacementRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#ef641f",
  },
  merchantRecommendedBadge: {
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
    color: "#18704b",
    backgroundColor: "#e6f6ee",
    fontSize: 7,
    fontWeight: "900",
  },
  merchantSubstitutionHistory: {
    gap: 5,
    padding: 11,
    borderRadius: 14,
    backgroundColor: "#f8f5f3",
  },
  merchantSubstitutionStatus: {
    alignSelf: "flex-start",
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 8,
  },
  merchantSubstitutionPending: { backgroundColor: "#fff0d9" },
  merchantSubstitutionAccepted: { backgroundColor: "#dcf6e8" },
  merchantSubstitutionRejected: { backgroundColor: "#f5e8e5" },
  merchantSubstitutionStatusText: { color: "#493c35", fontSize: 8, fontWeight: "900" },
  merchantRefundText: { color: "#13744d", fontSize: 11, fontWeight: "900" },
  merchantDetailError: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 11,
    borderRadius: 13,
    backgroundColor: "#fff0ec",
  },
  merchantDetailErrorText: {
    flex: 1,
    color: "#8e3322",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 16,
  },
  merchantDetailDelivery: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#f1edff",
  },
  merchantDetailChat: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 15,
    backgroundColor: "#7c3cff",
  },
  merchantAccountCard: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderRadius: 20,
    backgroundColor: "#211813",
  },
  merchantAccountIcon: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ef641f",
  },
  merchantAccountCopy: { flex: 1, gap: 3 },
  merchantAccountTitle: { color: "#211c18", fontSize: 14, fontWeight: "900" },
  merchantAccountDetail: { color: "#756c65", fontSize: 11, lineHeight: 16 },
  merchantAccountStatus: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    fontSize: 10,
    fontWeight: "900",
  },
  merchantAccountStatusOpen: { color: "#b9f4d2", backgroundColor: "rgba(45,177,108,.18)" },
  merchantAccountStatusPaused: { color: "#ffd0b6", backgroundColor: "rgba(239,100,31,.18)" },
  merchantAccountCardTitle: { color: "#fff", fontSize: 14, fontWeight: "900" },
  merchantAccountCardDetail: { color: "rgba(255,255,255,.6)", fontSize: 11, lineHeight: 16 },
  merchantBranchRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: "#eee8e3",
  },
  merchantBranchPin: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  merchantBranchPinOpen: { backgroundColor: "#e4f7ed" },
  merchantBranchPinClosed: { backgroundColor: "#fff0e6" },
  merchantBranchMeta: { marginTop: 3, color: "#ef641f", fontSize: 10, fontWeight: "800" },
  merchantDataCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 11,
    padding: 15,
    borderRadius: 18,
    backgroundColor: "#edf8f2",
    borderWidth: 1,
    borderColor: "#cce9da",
  },
  merchantBottomNav: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    paddingTop: 7,
    paddingBottom: Math.max(8, Platform.OS === "ios" ? 12 : 8),
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e7e0db",
    shadowColor: "#382116",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -4 },
    elevation: 16,
  },
  merchantBottomItem: {
    flex: 1,
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    borderRadius: 16,
    outlineWidth: 0,
    outlineStyle: "solid",
  },
  merchantBottomItemActive: { backgroundColor: "#fff3ec" },
  merchantBottomIconWrap: { position: "relative", minWidth: 30, alignItems: "center" },
  merchantBottomDot: {
    position: "absolute",
    top: -1,
    right: 1,
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#d94a31",
    borderWidth: 1,
    borderColor: "#fff",
  },
  merchantBottomLabel: { color: "#8b817b", fontSize: 10, fontWeight: "800" },
  merchantBottomLabelActive: { color: "#ef641f" },
  merchantHeroTopline: {
    position: "absolute",
    top: 18,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  merchantLiveDot: { width: 9, height: 9, borderRadius: 999 },
  merchantLiveDotOpen: { backgroundColor: "#64e49d" },
  merchantLiveDotPaused: { backgroundColor: "#ff9453" },
  merchantHeroMeta: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  merchantHeroMetaText: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    color: "#fff",
    backgroundColor: "rgba(255,255,255,.12)",
    fontSize: 11,
    fontWeight: "800",
  },
  merchantSync: {
    minHeight: 66,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  merchantSyncLive: { backgroundColor: "#f1fbf5", borderColor: "#c8ebd5" },
  merchantSyncError: { backgroundColor: "#fff2ef", borderColor: "#f2c7bd" },
  merchantSyncCopy: { flex: 1, gap: 3 },
  merchantSyncTitle: { color: "#201b18", fontSize: 13, fontWeight: "900" },
  merchantSyncDetail: { color: "#716862", fontSize: 11, lineHeight: 16 },
  merchantSyncButton: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eaded7",
  },
  merchantPulseCard: {
    padding: 16,
    borderRadius: 22,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ebe6e2",
    gap: 14,
    shadowColor: "#3a2315",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  merchantPulseHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  merchantPulseEyebrow: { color: "#f06720", fontSize: 10, fontWeight: "900", letterSpacing: 1.2 },
  merchantPulseTitle: { marginTop: 3, color: "#201b18", fontSize: 18, fontWeight: "900" },
  merchantPulseTotal: { color: "#756b65", fontSize: 11, fontWeight: "800" },
  merchantPulseGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  merchantPulseStage: {
    minWidth: "30%",
    flexGrow: 1,
    padding: 11,
    borderRadius: 15,
    backgroundColor: "#f7f4f1",
  },
  merchantPulseStageValue: { color: "#261d18", fontSize: 21, fontWeight: "900" },
  merchantPulseStageLabel: { marginTop: 2, color: "#766d67", fontSize: 10, fontWeight: "800" },
  merchantSlaAlert: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 11,
    borderRadius: 14,
    backgroundColor: "#fff0ec",
  },
  merchantSlaAlertText: {
    flex: 1,
    color: "#93301f",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
} as const;
