import bcrypt from "bcryptjs";

const asset = (id) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export function createSeed(now) {
  const createdAt = now();
  const password = bcrypt.hashSync("demo123", 10);
  return {
    meta: {
      name: "Flash Delivery Mobility",
      version: 4,
      createdAt,
      updatedAt: createdAt,
      database: "sqlite",
    },
    users: [
      {
        id: "usr_customer",
        name: "Alex Rivero",
        email: "cliente@flash.app",
        password,
        roles: ["customer"],
        phone: "+54 11 5555 0101",
        wallet: 18600,
        defaultAddress: "Defensa 982, San Telmo",
      },
      {
        id: "usr_merchant",
        name: "Sofia Campos",
        email: "comercio@flash.app",
        password,
        roles: ["merchant"],
        phone: "+54 11 5555 0202",
        wallet: 842000,
        restaurantId: "rest_roja",
      },
      {
        id: "usr_driver",
        name: "Lautaro Mendez",
        email: "conductor@flash.app",
        password,
        roles: ["driver"],
        phone: "+54 11 5555 0303",
        wallet: 38200,
        driverId: "drv_lautaro",
      },
      {
        id: "usr_admin",
        name: "Mila Torres",
        email: "ops@flash.app",
        password,
        roles: ["admin"],
        phone: "+54 11 5555 0404",
        wallet: 0,
      },
      {
        id: "usr_support",
        name: "Valentina Ruiz",
        email: "soporte@flash.app",
        password,
        roles: ["support"],
        phone: "+54 11 5555 0505",
        wallet: 0,
      },
    ],
    addresses: [
      {
        id: "addr_customer_home",
        userId: "usr_customer",
        label: "Casa",
        address: "Defensa 982, San Telmo",
        lat: -34.6177,
        lng: -58.3621,
        isDefault: true,
      },
      {
        id: "addr_customer_work",
        userId: "usr_customer",
        label: "Trabajo",
        address: "Av. Corrientes 900, Microcentro",
        lat: -34.6037,
        lng: -58.3816,
        isDefault: false,
      },
    ],
    paymentMethods: [
      {
        id: "pay_wallet",
        userId: "usr_customer",
        type: "wallet",
        label: "Flash Wallet",
        last4: "",
        balance: 18600,
        isDefault: true,
      },
      {
        id: "pay_card_7234",
        userId: "usr_customer",
        type: "card",
        label: "Mastercard",
        last4: "7234",
        balance: 0,
        isDefault: false,
      },
    ],
    walletTransactions: [
      {
        id: "wtx_seed_1",
        userId: "usr_customer",
        kind: "credit",
        amount: 18600,
        description: "Saldo demo inicial",
        createdAt,
      },
    ],
    restaurants: [
      {
        id: "rest_roja",
        ownerId: "usr_merchant",
        name: "Roja Beef House",
        cuisine: "Parrilla urbana",
        rating: 4.8,
        distanceKm: 1.2,
        etaMin: 22,
        deliveryFee: 790,
        open: true,
        image: asset("photo-1550547660-d9450f859349"),
        cover: asset("photo-1529692236671-f1f6cf9683ba"),
        badge: "2x1 en burgers",
        address: "Honduras 4120, Palermo",
        lat: -34.5886,
        lng: -58.4301,
        menu: [
          {
            id: "item_burger_brava",
            name: "Burger Brava",
            description: "Doble carne, cheddar, cebolla crispy y salsa ahumada.",
            category: "Burger",
            price: 6500,
            rating: 4.9,
            timeMin: 18,
            kcal: 780,
            stock: true,
            image: asset("photo-1568901346375-23c9450c58cd"),
            tags: ["Picante", "Mas vendido"],
          },
          {
            id: "item_papas_trufa",
            name: "Papas con trufa",
            description: "Papas rusticas, parmesano y alioli suave.",
            category: "Burger",
            price: 3200,
            rating: 4.7,
            timeMin: 12,
            kcal: 520,
            stock: true,
            image: asset("photo-1576107232684-1279f390859f"),
            tags: ["Combo"],
          },
          {
            id: "item_limonada_roja",
            name: "Limonada roja",
            description: "Frutilla, lima, menta y soda.",
            category: "Bebidas",
            price: 2100,
            rating: 4.6,
            timeMin: 5,
            kcal: 160,
            stock: true,
            image: asset("photo-1497534446932-c925b458314e"),
            tags: ["Fresco"],
          },
        ],
        extras: [
          { id: "extra_cheddar", name: "Cheddar extra", price: 550 },
          { id: "extra_palta", name: "Palta", price: 700 },
          { id: "extra_picante", name: "Salsa picante", price: 350 },
          { id: "extra_crispy", name: "Cebolla crispy", price: 320 },
        ],
      },
      {
        id: "rest_nori",
        ownerId: "usr_merchant",
        name: "Nori Club",
        cuisine: "Sushi & bowls",
        rating: 4.7,
        distanceKm: 2.1,
        etaMin: 29,
        deliveryFee: 890,
        open: true,
        image: asset("photo-1579584425555-c3ce17fd4351"),
        cover: asset("photo-1611143669185-af224c5e3252"),
        badge: "15% con wallet",
        address: "Armenia 1470, Palermo",
        lat: -34.5891,
        lng: -58.4251,
        menu: [
          {
            id: "item_salmon_furai",
            name: "Roll salmon furai",
            description: "Salmon, palta, queso crema y crocante panko.",
            category: "Sushi",
            price: 8200,
            rating: 4.8,
            timeMin: 22,
            kcal: 610,
            stock: true,
            image: asset("photo-1579871494447-9811cf80d66c"),
            tags: ["12 piezas", "Fresco"],
          },
          {
            id: "item_poke_verde",
            name: "Poke verde",
            description: "Arroz, edamame, mango, palta y salsa ponzu.",
            category: "Veggie",
            price: 7200,
            rating: 4.6,
            timeMin: 17,
            kcal: 560,
            stock: true,
            image: asset("photo-1547496502-affa22d38842"),
            tags: ["Veggie"],
          },
        ],
        extras: [
          { id: "extra_jengibre", name: "Jengibre extra", price: 280 },
          { id: "extra_wasabi", name: "Wasabi", price: 250 },
          { id: "extra_soja", name: "Salsa soja", price: 180 },
        ],
      },
      {
        id: "rest_forno",
        ownerId: "usr_merchant",
        name: "Forno Palermo",
        cuisine: "Pizza italiana",
        rating: 4.6,
        distanceKm: 1.8,
        etaMin: 24,
        deliveryFee: 690,
        open: true,
        image: asset("photo-1513104890138-7c749659a591"),
        cover: asset("photo-1565299624946-b28f40a0ae38"),
        badge: "Envio bajo",
        address: "Costa Rica 5032, Palermo",
        lat: -34.5845,
        lng: -58.4304,
        menu: [
          {
            id: "item_pizza_burrata",
            name: "Pizza burrata",
            description: "Tomates asados, pesto, burrata y masa madre.",
            category: "Pizza",
            price: 7600,
            rating: 4.9,
            timeMin: 19,
            kcal: 840,
            stock: true,
            image: asset("photo-1574071318508-1cdbab80d002"),
            tags: ["Nueva", "Cremosa"],
          },
          {
            id: "item_tiramisu",
            name: "Tiramisu express",
            description: "Mascarpone, cafe, cacao amargo y vainillas.",
            category: "Postres",
            price: 4100,
            rating: 4.8,
            timeMin: 8,
            kcal: 430,
            stock: true,
            image: asset("photo-1571877227200-a0d98ea607e9"),
            tags: ["Postre"],
          },
        ],
        extras: [
          { id: "extra_muzza", name: "Mozzarella extra", price: 680 },
          { id: "extra_albahaca", name: "Albahaca fresca", price: 220 },
        ],
      },
      {
        id: "rest_huerta",
        ownerId: "usr_merchant",
        name: "Huerta 9",
        cuisine: "Plant based",
        rating: 4.9,
        distanceKm: 0.9,
        etaMin: 17,
        deliveryFee: 590,
        open: true,
        image: asset("photo-1512621776951-a57141f2eefd"),
        cover: asset("photo-1543353071-10c8ba85a904"),
        badge: "Top saludable",
        address: "Chile 940, San Telmo",
        lat: -34.6164,
        lng: -58.3719,
        menu: [
          {
            id: "item_caesar_veggie",
            name: "Caesar veggie",
            description: "Kale, parmesano vegano, croutons y dressing citrico.",
            category: "Veggie",
            price: 5900,
            rating: 4.8,
            timeMin: 14,
            kcal: 420,
            stock: true,
            image: asset("photo-1540420773420-3366772f4999"),
            tags: ["Ligero", "Sin carne"],
          },
          {
            id: "item_smoothie_rojo",
            name: "Smoothie rojo",
            description: "Frutilla, banana, hibiscus y granola crocante.",
            category: "Bebidas",
            price: 3600,
            rating: 4.7,
            timeMin: 7,
            kcal: 310,
            stock: true,
            image: asset("photo-1505252585461-04db1eb84625"),
            tags: ["Bebida"],
          },
        ],
        extras: [
          { id: "extra_granola", name: "Granola", price: 420 },
          { id: "extra_proteina", name: "Proteina vegetal", price: 900 },
        ],
      },
    ],
    drivers: [
      {
        id: "drv_lautaro",
        userId: "usr_driver",
        name: "Lautaro Mendez",
        online: true,
        serviceModes: ["delivery", "ride"],
        activeService: "delivery",
        vehicle: "Moto Honda Wave",
        plate: "A123BCD",
        rating: 4.96,
        location: { lat: -34.5886, lng: -58.4301, label: "Palermo" },
        earningsToday: 38200,
      },
      {
        id: "drv_mica",
        userId: "usr_driver",
        name: "Mica Alvarez",
        online: true,
        serviceModes: ["ride"],
        activeService: "ride",
        vehicle: "Toyota Etios",
        plate: "AD456EF",
        rating: 4.91,
        location: { lat: -34.6037, lng: -58.3816, label: "Centro" },
        earningsToday: 51700,
      },
      {
        id: "drv_nico",
        userId: "usr_driver",
        name: "Nico Pereyra",
        online: false,
        serviceModes: ["delivery"],
        activeService: "delivery",
        vehicle: "Bicicleta electrica",
        plate: "BIKE-19",
        rating: 4.82,
        location: { lat: -34.6177, lng: -58.3621, label: "San Telmo" },
        earningsToday: 18400,
      },
    ],
    orders: [
      {
        id: "ORD-7301",
        customerId: "usr_customer",
        restaurantId: "rest_nori",
        courierId: null,
        status: "ready_for_pickup",
        deliveryAddress: "Defensa 982, San Telmo",
        paymentMethod: "Flash Wallet",
        items: [
          {
            menuItemId: "item_salmon_furai",
            name: "Roll salmon furai",
            quantity: 1,
            unitPrice: 8200,
            extras: ["Wasabi"],
            note: "Salsa aparte",
          },
          {
            menuItemId: "item_poke_verde",
            name: "Poke verde",
            quantity: 1,
            unitPrice: 7200,
            extras: [],
            note: "",
          },
        ],
        subtotal: 15400,
        deliveryFee: 890,
        serviceFee: 520,
        total: 16810,
        etaMin: 14,
        createdAt,
        timeline: [
          { status: "accepted", at: createdAt },
          { status: "preparing", at: createdAt },
          { status: "ready_for_pickup", at: createdAt },
        ],
      },
      {
        id: "ORD-7302",
        customerId: "usr_customer",
        restaurantId: "rest_roja",
        courierId: "drv_lautaro",
        status: "delivering",
        deliveryAddress: "Defensa 982, San Telmo",
        paymentMethod: "Mastercard 7234",
        items: [
          {
            menuItemId: "item_burger_brava",
            name: "Burger Brava",
            quantity: 2,
            unitPrice: 6500,
            extras: ["Cheddar extra"],
            note: "",
          },
        ],
        subtotal: 13550,
        deliveryFee: 790,
        serviceFee: 520,
        total: 14860,
        etaMin: 11,
        createdAt,
        timeline: [
          { status: "accepted", at: createdAt },
          { status: "preparing", at: createdAt },
          { status: "ready_for_pickup", at: createdAt },
          { status: "courier_assigned", at: createdAt },
          { status: "picked_up", at: createdAt },
          { status: "delivering", at: createdAt },
        ],
      },
    ],
    rides: [
      {
        id: "RIDE-2201",
        customerId: "usr_customer",
        driverId: "drv_mica",
        status: "arriving",
        service: "comfort",
        pickup: "Defensa 982, San Telmo",
        destination: "Aeroparque Jorge Newbery",
        distanceKm: 9.8,
        etaMin: 7,
        durationMin: 24,
        fare: 8920,
        paymentMethod: "Flash Wallet",
        createdAt,
        timeline: [
          { status: "requested", at: createdAt },
          { status: "driver_assigned", at: createdAt },
          { status: "arriving", at: createdAt },
        ],
      },
    ],
    promotions: [
      {
        id: "promo_food_40",
        title: "40% off en seleccionados",
        description: "Tope de reintegro $4.000 con Flash Wallet.",
        service: "food",
        discountPercent: 40,
        active: true,
      },
      {
        id: "promo_ride_airport",
        title: "Viajes al aeropuerto",
        description: "Precio dinamico protegido hasta las 20:00.",
        service: "ride",
        discountPercent: 15,
        active: true,
      },
    ],
    supportTickets: [
      {
        id: "TCK-4401",
        service: "food",
        status: "open",
        title: "Pedido demorado",
        priority: "medium",
      },
      {
        id: "TCK-4402",
        service: "ride",
        status: "open",
        title: "Objeto olvidado",
        priority: "high",
      },
    ],
    notifications: [
      {
        id: "NTF-DEMO-ORDER",
        userId: "usr_customer",
        channel: "in_app",
        template: "order_status",
        payload: { orderId: "ORD-7301", status: "delivering", etaMin: 18 },
        status: "sent",
        readAt: null,
        createdAt,
      },
      {
        id: "NTF-DEMO-RIDE",
        userId: "usr_customer",
        channel: "in_app",
        template: "ride_status",
        payload: { rideId: "RIDE-2201", status: "arriving", etaMin: 6 },
        status: "sent",
        readAt: createdAt,
        createdAt,
      },
    ],
    notificationPreferences: notificationPreferenceCategories.map((category) => ({
      userId: "usr_customer",
      category,
      pushEnabled: category !== "promotions",
      emailEnabled: false,
      updatedAt: null,
    })),
    ratings: [
      {
        id: "rate_roja",
        targetType: "restaurant",
        targetId: "rest_roja",
        userId: "usr_customer",
        score: 5,
        comment: "Muy rapido",
        createdAt,
      },
    ],
    zones: [
      {
        id: "zone_palermo",
        name: "Palermo",
        demandLevel: "high",
        deliveryMultiplier: 1.2,
        rideMultiplier: 1.15,
        activeOrders: 18,
        activeRides: 9,
      },
      {
        id: "zone_centro",
        name: "Centro",
        demandLevel: "medium",
        deliveryMultiplier: 1.05,
        rideMultiplier: 1.12,
        activeOrders: 12,
        activeRides: 14,
      },
      {
        id: "zone_santelmo",
        name: "San Telmo",
        demandLevel: "medium",
        deliveryMultiplier: 1.08,
        rideMultiplier: 1.04,
        activeOrders: 8,
        activeRides: 5,
      },
    ],
    auditEvents: [
      {
        id: "audit_seed",
        actorId: "usr_admin",
        entityType: "platform",
        entityId: "seed",
        action: "seed_database",
        payload: { version: 3 },
        createdAt,
      },
    ],
  };
}

export function ensureBootstrapSupportUser(database, now, seedFactory = createSeed) {
  const support = seedFactory(now).users.find((user) => user.roles?.includes("support"));
  if (!support) return;
  const byEmail = database.prepare("SELECT id FROM users WHERE email = ?").get(support.email);
  if (!byEmail && !database.prepare("SELECT id FROM users WHERE id = ?").get(support.id)) {
    database
      .prepare(
        `INSERT INTO users (
          id, name, email, password_hash, phone, wallet, default_address, restaurant_id, driver_id, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        support.id,
        support.name,
        support.email,
        support.password,
        support.phone || null,
        support.wallet || 0,
        support.defaultAddress || null,
        support.restaurantId || null,
        support.driverId || null,
        support.createdAt || now(),
      );
  }
  const user = database.prepare("SELECT id FROM users WHERE email = ?").get(support.email);
  if (user) {
    database
      .prepare("INSERT OR IGNORE INTO user_roles (user_id, role) VALUES (?, ?)")
      .run(user.id, "support");
  }
}

export function ensureLocalNotificationData(database, now, seedFactory = createSeed) {
  const customer = database.prepare("SELECT id FROM users WHERE id = ?").get("usr_customer");
  if (
    customer &&
    database.prepare("SELECT COUNT(*) AS total FROM notifications").get().total === 0
  ) {
    const seed = seedFactory(now);
    const insert = database.prepare(`
      INSERT OR IGNORE INTO notifications (id, user_id, channel, template, payload_json, status, read_at, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);
    for (const notification of seed.notifications || []) {
      insert.run(
        notification.id,
        notification.userId,
        notification.channel,
        notification.template,
        JSON.stringify(notification.payload || {}),
        notification.status,
        notification.readAt || null,
        notification.createdAt,
      );
    }
  }
}
