#!/bin/sh
set -eu

: "${FLASH_RUNTIME_PASSWORD:?FLASH_RUNTIME_PASSWORD is required}"
: "${FLASH_AUDIT_PASSWORD:?FLASH_AUDIT_PASSWORD is required}"
: "${FLASH_MIGRATION_PASSWORD:?FLASH_MIGRATION_PASSWORD is required}"

psql --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=migration_password="$FLASH_MIGRATION_PASSWORD" \
  --set=runtime_password="$FLASH_RUNTIME_PASSWORD" \
  --set=audit_password="$FLASH_AUDIT_PASSWORD" <<'SQL'
CREATE ROLE flash_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD :'migration_password';
CREATE ROLE flash_runtime LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD :'runtime_password';
CREATE ROLE flash_rls_audit LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS PASSWORD :'audit_password';
ALTER DATABASE :"DBNAME" OWNER TO flash_app;
SQL
